add header for file exporter.
open-telemetry/opentelemetry-collector-contrib pull request #10175
Opened 2022-05-20 00:10 UTC by Frapschen

**Description:** <Describe what has changed.>
I add a header for file exporter, pls review :)

2022-05-25 00:12 UTC, Frapschen commented
hi, pls review :)

2022-05-25 00:51 UTC, TylerHelmuth approved these changes
/cc @pmm-sumo as code owner

2022-05-30 12:21 UTC, pmm-sumo commented on exporter/fileexporter/README.md
> +| Stability                | [beta]                 |
```suggestion
| Stability                | [alpha]                 |
```

2022-05-30 12:24 UTC, pmm-sumo requested changes
I believe we should consider it an `alpha` exporter.

This is hinted by the documentation:

> Please note that there is no guarantee that exact field names will remain stable. This intended for primarily for debugging Collector without setting up backends.

2022-05-31 07:44 UTC, Frapschen commented
@pmm-sumo done.

2022-05-31 07:54 UTC, mx-psi approved these changes

2022-05-31 15:03 UTC, pmm-sumo approved these changes

2022-05-31 19:16 UTC, codeboten commented on exporter/fileexporter/README.md
> +| Stability                | [alpha]                 |
```suggestion
| Stability                | [alpha]                |
```

2022-05-31 19:18 UTC, codeboten commented on exporter/fileexporter/README.md
> +| Distributions            | [contrib]              |
```suggestion
| Status                   |                       |
| ------------------------ |-----------------------|
| Stability                | [alpha]               |
| Supported pipeline types | traces, metrics, logs |
| Distributions            | [core], [contrib]     |
```

2022-05-31 19:18 UTC, codeboten commented on exporter/fileexporter/README.md
> +[contrib]:https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib
```suggestion
[contrib]:https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib
[core]:https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol
```

2022-05-31 19:48 UTC, merged