Fix history min and max calculation
open-telemetry/opentelemetry-collector-contrib pull request #10257
Opened 2022-05-24 07:29 UTC by tyrone-anz

**Description:** 
Dynatrace exporter is rejecting histogram metrics because the exported min and max are sometimes not following `min <= avg <= max` rule.

![image](https://user-images.githubusercontent.com/64765107/169973507-451c1931-272e-4af8-a259-8b30d83870b9.png)

The fix would set the estimated min to use average when greater than it, and max to use average when less than it.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:**

Unit test is added

**Documentation:**

2022-05-25 12:17 UTC, dyladan approved these changes
Approving % changelog nit

2022-05-25 12:17 UTC, dyladan commented on CHANGELOG.md
> +- `dynatraceexporter`: Fix issue on histogram min and max calculation. (#10257)
Not a very descriptive changelog entry for end users. What specifically was fixed?

```suggestion
- `dynatraceexporter`: Ensure min is always less than or equal to mean and max is always greater or equal to mean for histogram estimation. (#10257)
```

2022-05-25 12:19 UTC, dyladan requested changes
Sorry after approving I realized that the `sum` also needs to be checked. In the case that the histogram has been seeded with negative values, the `sum` may be less than the `mean` and the upper bound of the smallest bucket, which would also fail the consistency check.

2022-05-25 12:33 UTC, dyladan approved these changes
Approval was right the first time

2022-05-25 15:02 UTC, arminru approved these changes
Thank you, @tyrone-anz!

2022-05-25 20:54 UTC, tyrone-anz commented
Thanks, everyone. Had to merge some conflict. May I get some approval to run the workflows?

2022-06-01 19:58 UTC, codeboten approved these changes

2022-06-01 19:58 UTC, merged