[docs] Add status header for parquet exporter
open-telemetry/opentelemetry-collector-contrib pull request #10328
Opened 2022-05-25 08:55 UTC by Frapschen

**Description:** <Describe what has changed.>
Add status header for parquet exporter

2022-05-25 12:28 UTC, pmm-sumo commented on exporter/parquetexporter/README.md
> +| Stability                | [beta]               |
```suggestion
| Stability                | [in development]               |
```

2022-05-25 12:28 UTC, pmm-sumo commented on exporter/parquetexporter/README.md
> +[beta]:https://github.com/open-telemetry/opentelemetry-collector#beta
```suggestion
[in-development]:https://github.com/open-telemetry/opentelemetry-collector#in-development
```

2022-05-25 12:29 UTC, pmm-sumo requested changes
This one is not even functional, we should use "in-development" status

2022-05-25 20:56 UTC, codeboten commented on exporter/parquetexporter/README.md
> +| Distributions            | [contrib]            |
Currently this component is not in contrib

```suggestion
| Distributions            | none                 |
```

2022-05-26 13:29 UTC, pmm-sumo commented on exporter/parquetexporter/README.md
>  The full list of settings exposed for this exporter are documented [here](config.go)
This is a dead link, I suggest to fix it. Perhaps using that way:

```suggestion
The full list of settings exposed for this exporter is going to be documented later
```

2022-05-26 13:30 UTC, pmm-sumo approved these changes
The change looks good overall

2022-05-26 15:40 UTC, codeboten approved these changes

2022-05-26 15:40 UTC, merged