Add status header for journald receiver
open-telemetry/opentelemetry-collector-contrib pull request #10462
Opened 2022-05-31 07:28 UTC by Frapschen

**Description:** <Describe what has changed.>
Add status header for journald receiver

2022-05-31 19:03 UTC, codeboten requested changes
Please remove line 13, otherwise this looks good

2022-05-31 19:03 UTC, codeboten commented on receiver/journaldreceiver/README.md
>  Supported pipeline types: logs
This can be removed

2022-06-01 01:37 UTC, Frapschen commented on receiver/journaldreceiver/README.md
>  Supported pipeline types: logs
done

2022-06-01 16:46 UTC, codeboten approved these changes

2022-06-01 20:36 UTC, merged