googlecloudpubsub receiver: allow endpoint and insecure config
open-telemetry/opentelemetry-collector-contrib pull request #10845
Opened 2022-06-08 22:39 UTC by k7k0

**Description:** <Describe what has changed.>
Fixes #10844 allowing to connect the receiver to a local PubSub emulator instance or switching between [global and regional service endpoints](https://cloud.google.com/pubsub/docs/reference/service_apis_overview#service_endpoints)

**Link to tracking Issue:** #10844

**Testing:** tested locally by [running  the emulator](https://cloud.google.com/pubsub/docs/emulator) and configuring the receiver with
```
receivers:
  googlecloudpubsub:
    project: "project-id"
    endpoint: localhost:8085
    insecure: true
```

**Documentation:** Added config doc for both params

2022-06-10 21:37 UTC, alexvanboxel approved these changes

2022-06-10 21:37 UTC, alexvanboxel commented on receiver/googlecloudpubsubreceiver/README.md
> +  or switching between [global and regional service endpoints](https://cloud.google.com/pubsub/docs/reference/service_apis_overview#service_endpoints).
never used the regional endpoints, so I tried the out of curiosity. Verified the branch locally and worked (as well with a regional endpoint)

2022-06-11 17:51 UTC, alexvanboxel commented
@djaglowski can you kick off the tests? thanks.

2022-06-13 15:01 UTC, alexvanboxel requested changes

2022-06-13 15:22 UTC, k7k0 commented
fixed tests. @djaglowski can you kick off again? thanks.

2022-06-13 16:14 UTC, alexvanboxel approved these changes

2022-06-13 16:19 UTC, djaglowski commented
This looks good to me, but would appreciate a final review from @alexvanboxel before I merge it.

2022-06-13 16:53 UTC, alexvanboxel commented
> This looks good to me, but would appreciate a final review from @alexvanboxel before I merge it.

already did and tested. Tests give a changelog error though

2022-06-13 16:58 UTC, djaglowski commented
@k7k0, please add a changelog entry.

2022-06-13 18:22 UTC, alexvanboxel approved these changes

2022-06-13 18:24 UTC, djaglowski approved these changes

2022-06-13 18:24 UTC, alexvanboxel commented
all green, now only need approval from allowed approvers

2022-06-13 18:24 UTC, merged