[docs]Add status header for httpforwarder
open-telemetry/opentelemetry-collector-contrib pull request #11138
Opened 2022-06-18 04:49 UTC by my-git9

Add status header for httpforwarder

fix part of:https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10116

2022-06-18 17:14 UTC, TylerHelmuth requested changes
This extension needs to be marked as unmaintained not beta: https://github.com/open-telemetry/opentelemetry-collector#unmaintained

2022-06-21 04:59 UTC, my-git9 commented
/cc @TylerHelmuth @codeboten

2022-06-21 15:41 UTC, TylerHelmuth approved these changes

2022-06-21 15:53 UTC, codeboten approved these changes

2022-06-22 12:18 UTC, merged