[docs] add status header for schemaprocessor
open-telemetry/opentelemetry-collector-contrib pull request #12132
Opened 2022-07-06 18:10 UTC by codeboten

Fixes #12131

2022-07-07 03:18 UTC, TylerHelmuth approved these changes

2022-07-07 13:18 UTC, mx-psi requested changes

2022-07-07 16:57 UTC, codeboten commented on processor/schemaprocessor/README.md
> +| Supported pipeline types | traces, logs     |
@mx-psi fixed!

2022-07-08 07:40 UTC, mx-psi approved these changes

2022-07-08 07:41 UTC, merged