[processor/resourcedetection] Add back `host.name` on GKE
open-telemetry/opentelemetry-collector-contrib pull request #12355
Opened 2022-07-13 10:26 UTC by mx-psi

**Description:** 

Adds back the `host.name` attribute (coming from `instance/hostname`) when running on GKE.

This metadata endpoint is available on GKE nodes of any type, and it was possible to have this attribute on GKE before #10347

**Link to tracking Issue:** Fixes #12354

2022-07-13 13:12 UTC, dashpole requested changes
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10486#issue-1256314869.  It unfortunately isn't available on GKE when using workload identity.

2022-07-13 14:07 UTC, dashpole commented
It isn't really possible for the collector to know.  The GCE metadata endpoints just won't be available in that case.

2022-07-22 12:06 UTC, mx-psi commented
I added a `addFallible` method to the builder, so that the error is only logged when `GCEHostname` fails and does not make the whole processor fail. Is this solution acceptable to you @dashpole?

I understand that this can be also gathered through the downward API, but our biggest issue with users is currently misconfigurations and this makes it a lot easier (and restores the behavior that existed before when not using workload identity and was removed without prior warning).

2022-07-22 15:01 UTC, dashpole approved these changes

2022-07-22 15:38 UTC, merged