[datadogexporter] Send host metadata
open-telemetry/opentelemetry-collector-contrib pull request #1351
Opened 2020-10-22 15:37 UTC by mx-psi

**Description:** <Describe what has changed.>

- Get hostname and instance ID from EC2 instance metadata if available.

- When either the metrics or traces exporter in the Datadog exporter are started, a single goroutine is created that sends host metadata (currently comprised of: EC2 instance metadata, tags and OS metadata) to our backend every 30 minutes. This goroutine is stopped at shutdown. This is controlled by a (opt-out) flag.

**Link to tracking Issue:** n/a
**Testing:** Added some unit tests, amended existing ones, tested on an EC2 instance against Datadog's backend.
**Documentation:** Documented public functions

2020-10-23 09:56 UTC, ericmustin approved these changes
lgtm 👍 , we may need to update the example and test yaml though?

2020-10-23 09:59 UTC, ericmustin commented
(disregard the bit about needing to update the yaml, lgtm)

2020-10-23 14:04 UTC, mx-psi commented on exporter/datadogexporter/utils/http.go
> +	Version   = "0.13.1"
Note: Ideally this would use `internal/version`'s `Version` but this is not possible as of now (see #1347)

2020-10-23 15:28 UTC, KSerrania approved these changes
LGTM, left a few nits

2020-10-23 15:28 UTC, KSerrania commented on exporter/datadogexporter/metadata/metadata.go
> +// hostMetadata includes metadata about the host tags,
```suggestion
// HostMetadata includes metadata about the host tags,
```

2020-10-23 15:28 UTC, KSerrania commented on exporter/datadogexporter/metadata/metadata.go
> +// hostTags are the host tags.
```suggestion
// HostTags are the host tags.
```

2020-10-23 15:28 UTC, KSerrania commented on exporter/datadogexporter/metadata/metadata.go
> +// meta includes metadata about the host aliases
```suggestion
// Meta includes metadata about the host aliases
```

2020-10-23 15:31 UTC, mx-psi commented on exporter/datadogexporter/config/config.go
> +// GetHostmTags gets the host tags extracted from the configuration
```suggestion
// GetHostTags gets the host tags extracted from the configuration
```

2020-10-23 15:32 UTC, mx-psi commented on exporter/datadogexporter/go.mod
> +  github.com/aws/aws-sdk-go v1.34.9
Fixed!

2020-10-23 15:32 UTC, mx-psi commented
This is now reviewable by maintainers

2020-10-23 17:17 UTC, bogdandrutu approved these changes

2020-10-23 17:18 UTC, bogdandrutu requested changes
Is this not a duplicate of the https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/resourcedetectionprocessor? why do we have duplicate functionality? Can you use that?

2020-10-26 09:06 UTC, mx-psi commented
>Is this not a duplicate of the https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/resourcedetectionprocessor? why do we have duplicate functionality? Can you use that?

@bogdandrutu No: there is some overlap on the information this PR and the resource detector gather, but at least some goals are different. This PR aims to

1. send metadata to Datadog that includes: a) all host names of the host (including, if available, EC2 hostname and instance id), b) some user-set metadata about the host and c) some info about the version and kind of component and
2. set the hostname in metrics and traces to an EC2 one if available.

We use metadata from (1) to make sure that host names that refer to the same host are identified as such, since this impacts usability and billing. This is **not** covered by the resource detection processor: it sends data to Datadog and it is not attached to metrics/traces.

Aim (2) could be covered by the resource detection processor (and I want to open a PR to make use of the metadata from this component in the future), but, since we had the EC2 information available from (1) I thought it made sense to add it here too: for usability we must send telemetry data with some host name so this would be a last resort mechanism to get a coherent hostname.

2020-10-26 14:17 UTC, KSerrania approved these changes

2020-10-26 18:54 UTC, bogdandrutu commented
@mx-psi please at least consider to create an issue, to understand how can we remove duplicate code, and how can we share the functionality at least between the processor and this exporter.

Once the issue is created and assign to you :) I will merge this :)

2020-10-26 19:46 UTC, ericmustin commented
@bogdandrutu one thing to note here is that, even _if_ a processor could do all of these things, the issue is that exporters can not create/control processors (or other components) on their own. It requires user configuration. And in general asking users to setup multiple pieces of a pipeline increases the room for error/mistakes.

Something to keep in mind as I think i've seen a few use cases now where it would be nice to have an option that would allow exporters to have more control over the whole pipeline.

2020-10-26 22:07 UTC, bogdandrutu commented
@ericmustin good observation, that is one of the reason some companies decided to ship their own distribution of the collector, which is in a sense just the collector with a builtin configuration. We can discuss about that as well I think.

2020-10-26 23:38 UTC, jrcamp commented
> @bogdandrutu one thing to note here is that, even _if_ a processor could do all of these things, the issue is that exporters can not create/control processors (or other components) on their own. It requires user configuration. And in general asking users to setup multiple pieces of a pipeline increases the room for error/mistakes.
> 
> Something to keep in mind as I think i've seen a few use cases now where it would be nice to have an option that would allow exporters to have more control over the whole pipeline.

Is this about detecting metadata for ec2, gcp, etc.? There is an OTEP that has been accepted for this (https://github.com/open-telemetry/oteps/blob/master/text/0111-auto-resource-detection.md). I think the long term plan would be to implement this which the resourcedetectionprocessor could use as well as other components that needed it. Perhaps there could be an extension that you configure once that exporters and processors could centrally source the metadata from.

@james-bebbington any progress on the autodetection API?

2020-10-27 09:11 UTC, james-bebbington commented
> @james-bebbington any progress on the autodetection API?

The spec for that was merged here: https://github.com/open-telemetry/opentelemetry-specification/pull/811

But in the end I don't think there's too much value using that in the collector. We may as well continue with the resource detection processor as is imo.

2020-10-27 09:31 UTC, mx-psi commented
> @mx-psi please at least consider to create an issue, to understand how can we remove duplicate code, and how can we share the functionality at least between the processor and this exporter

@bogdandrutu I created issue #1379 to track this overlapping functionality; let me know if I should expand/modify this in any way. I can't assign it to me but feel free to do so when you read this.

2020-10-27 16:36 UTC, mx-psi commented
CI keeps failing because of a flaky load test and a flaky unit test (the latter I believe is being fixed on #1384). I am going to try a couple times to see if I can fix it

2020-10-28 19:57 UTC, bogdandrutu approved these changes

2020-10-28 19:57 UTC, merged