[transformprocessor] Add TQL mapping functions for InstrumentationScope attributes
open-telemetry/opentelemetry-collector-contrib pull request #13640
Opened 2022-08-26 15:45 UTC by pirgeo

**Description:**
Adds mapping functions for InstrumentationLibraryScope.

**Link to tracking Issue:** 
Resolves #13639 

**Documentation:** Updated the respective README.md files.

2022-08-26 15:53 UTC, TylerHelmuth approved these changes
Thanks for keeping the TQL up-to-date with the Spec!

2022-08-26 15:53 UTC, TylerHelmuth commented
@pirgeo please add a changelog entry for this change

2022-08-26 16:01 UTC, TylerHelmuth commented on unreleased/instrumentation-scope-attributes.yaml
> +component: transformprocessor
```suggestion
component: pkg/telemetryquerylanguage
```

2022-08-26 16:05 UTC, TylerHelmuth approved these changes

2022-08-26 20:42 UTC, bogdandrutu requested changes, later dismissed
Blocking this because we need to stop adding copy paste code. Waiting for https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13650

2022-08-29 17:06 UTC, bogdandrutu commented
@pirgeo please rebase this.

2022-08-29 18:13 UTC, pirgeo commented
Since the underlying change made this a very small change, I reorganized the commits a bit.

2022-08-29 18:26 UTC, TylerHelmuth reviewed
Can you add new tests scenarios in scope_test.go for the new getters/setters?

2022-08-30 14:28 UTC, TylerHelmuth approved these changes

2022-08-30 14:28 UTC, TylerHelmuth commented
@pirgeo can you address the build failures?

2022-08-30 20:03 UTC, bogdandrutu approved these changes

2022-08-30 20:03 UTC, merged