[exporter/datadogexporter] Do not validate key if the result will not be checked
open-telemetry/opentelemetry-collector-contrib pull request #13732
Opened 2022-08-30 14:47 UTC by craigandrews

**Description:** <Describe what has changed.>

In the DataDog exporter, for both traces and metrics, the API Key validation is being run and then, if the fail_on_invalid_key option is set, the result is thrown away. This PR prevents the validation from running at all if the error would be ignored. With both traces and metrics enabled, this can speed up the startup of the exporter by up to 1 second.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

2022-09-05 15:00 UTC, mx-psi requested changes
Thanks for your contribution @craigandrews! Note that when `api::fail_on_invalid_key` is false, we still log the result of the API key validation: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/internal/utils/api.go#L43. This is useful for users to more easily catch soon when API errors are  due to the API key being invalid and we want to keep this behavior, so I am afraid we can't accept your PR as-is.

If your concern is that the `utils.ValidateAPIKey` check significantly impacts the start time of the Datadog exporter, we could run the API check on a separate goroutine when `api::fail_on_invalid_key` is `false`. Would that work for you?

I am also interested in understanding what is your use case to see if we can further help/prioritize other work to improve the start time. In particular: What environment are you running the Collector on? What issues are you seeing due to the delayed startup of the Datadog exporter?

2022-09-26 14:40 UTC, mx-psi commented
@craigandrews any thoughts on the above?

2022-09-26 17:29 UTC, mx-psi commented
Okay, that's a fair reason to move this check into its own goroutine. I will create a card in our backlog to get around to doing this eventually.

2022-10-25 05:45 UTC, closed without merging

2022-11-24 15:34 UTC, RangelReale commented
I'm having the same problem, my Lambda initialization frequently times out on the API key check call, I think doing this in a goroutine if not set to fail would be a good change, as the only purpose in this cause would be to log an error.