[confmap.provider/s3provider] Rename from s3mapprovider to s3provider
open-telemetry/opentelemetry-collector-contrib pull request #14617
Opened 2022-09-30 16:16 UTC by neelayu

**Description:** <Describe what has changed.>
For consistency, its better to keep it as `s3provider`. Also improved comments in the code, few minor changes and added unit tests

**Link to tracking Issue:** #14616

**Testing:** Added a few unit tests to increase coverage

**Documentation:** Updated README.md

2022-10-01 16:00 UTC, bogdandrutu approved these changes

2022-10-07 22:05 UTC, Aneurysm9 requested changes
There appear to be a number of changes that are not related to renaming the package.  Can you please split them into a separate PR?

2022-10-10 05:12 UTC, neelayu commented
@Aneurysm9 thanks for the feedback. This PR now only contains rename changes. I'll create a separate PR which will modify the minor bits here and there.

2022-10-10 22:29 UTC, Aneurysm9 approved these changes

2022-10-11 15:26 UTC, merged