Remove samplerate property from honeycomb exporter
open-telemetry/opentelemetry-collector-contrib pull request #1583
Opened 2020-11-13 16:34 UTC by MikeGoldsmith

Sampling should not be performed as part of the export process. If sampling is wanted to be used, it should be done with a sampling span processor earlier in the collector pipeline.

2020-11-13 16:37 UTC, paulosman approved these changes

2020-11-13 16:48 UTC, bogdandrutu approved these changes

2020-11-13 18:05 UTC, MikeGoldsmith commented
Please pause on merginf this. I want to add tests for existing users and if it'll break with existing configs that have the sample rate property.

2020-11-13 20:32 UTC, bogdandrutu commented
@MikeGoldsmith consider to use "request changes" to block a merge, you are lucky that I read the comment :)

2020-11-13 20:33 UTC, bogdandrutu requested changes, later dismissed
Blocking merge per @MikeGoldsmith request

2020-11-13 21:15 UTC, MikeGoldsmith commented
Thanks @bogdandrutu  - I'll do a request changes review next time 👍

2020-11-16 09:58 UTC, jpkrohling commented
This is assigned to me but I unable to review it today.

2020-11-16 15:06 UTC, MikeGoldsmith commented
I should get time to add tests either today or tomorrow. I'll leave a message when we're ready for this to be merged. Thanks

2020-11-17 19:26 UTC, MikeGoldsmith commented
This is ready for re-review / merging. I've re-added `sampleRate` to the config struct so to not break any existing configs and added comments to say it's usage is deprecated.

@bogdandrutu @jpkrohling

2020-11-19 14:49 UTC, bogdandrutu approved these changes

2020-11-19 18:48 UTC, merged