Fix Zipkin V1 receiver creating invalid timestamps
open-telemetry/opentelemetry-collector-contrib pull request #16062
Opened 2022-11-03 17:51 UTC by indrekj

I think this issue was introduced in d31a5c3f446fa1c5beec5381e923c9ff470ba632.

I [noticed a memory leak][1] in DataDog exporter but after a lot of debugging, it turned out that the OpenTelemetry gateway was receiving invalid timestamps:

```
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope
Span #0
    Trace ID       : 0000000000000000c20a2b82c179228a
    Parent ID      :
    ID             : 7c3415ed370f1777
    Name           : [redacted]
    Kind           : SPAN_KIND_SERVER
    Start time     : 2200-11-16 22:32:41.14035456 +0000 UTC
    End time       : 2200-11-16 22:33:02.68735456 +0000 UTC
```

The year is almost 100 years in the future.

Before we send a span to the gateway, it goes through an OpenTelemetry collector sidecar. We use Zipkin V1 endpoint to send the spans to the sidecar.

In the same pod, we're also using Zipkin V2 which did not have any issues.

The problem itself: zipkin uses microseconds. This has to be multipled with 1e3 to get nanoseconds, not with 1e6.

[1]: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15720

2022-11-05 11:28 UTC, indrekj commented
As a workaround, until this is merged is to use v0.61.0, which does not have this issue.

2022-11-07 17:17 UTC, bogdandrutu requested changes

2022-11-07 17:17 UTC, bogdandrutu commented on pkg/translator/zipkin/zipkinv1/json.go
> +	return pcommon.Timestamp(uint64(msecs) * 1e3)
It looks like the name of the func is wrong, but the timestamp is in usec, see https://github.com/openzipkin/zipkin-api/blob/master/zipkin-api.yaml#L385

2022-11-07 17:19 UTC, bogdandrutu approved these changes

2022-11-07 17:19 UTC, bogdandrutu commented on pkg/translator/zipkin/zipkinv1/json.go
> +	return pcommon.Timestamp(uint64(msecs) * 1e3)
Talked too soon, you are correct we convert to nanos, so `1e3` is correct.

2022-11-07 17:19 UTC, merged