awsemf-exporter: replace pattern "{{ }}" with "{ }"
open-telemetry/opentelemetry-collector-contrib pull request #1661
Opened 2020-11-20 19:02 UTC by hossain-rayhan

This contribution replace `ClusterName` and `TaskId` placeholder pattern `{{ }}` with `{ }`. AWS SSM parameter doesn't support the pattern `{{ }}`- so we need to update this.

2020-11-20 19:21 UTC, hossain-rayhan commented
@bogdandrutu and @tigrannajaryan can anybody please help me to get this reviewed and merged today. Its a one line change- replace `{{ }}` with `{ }`. Will highly appreciate.

2020-11-20 20:39 UTC, kbrockhoff requested changes

2020-11-20 20:39 UTC, kbrockhoff commented on exporter/awsemfexporter/emf_exporter_test.go
> +	expCfg.LogStreamName = "{WorngKey}"
Need to fix spelling to match below

2020-11-20 20:39 UTC, kbrockhoff commented on exporter/awsemfexporter/emf_exporter_test.go
> +	pusher, ok := streamToPusherMap["{WorngKey}"]
Need to fix spelling to match below

2020-11-20 20:51 UTC, hossain-rayhan commented on exporter/awsemfexporter/emf_exporter_test.go
> +	expCfg.LogStreamName = "{WorngKey}"
Updated.

2020-11-20 20:51 UTC, hossain-rayhan commented on exporter/awsemfexporter/emf_exporter_test.go
> +	pusher, ok := streamToPusherMap["{WorngKey}"]
Updated.

2020-11-20 21:14 UTC, kbrockhoff approved these changes

2020-11-20 21:15 UTC, kbrockhoff commented
@jrcamp this is ready to merge

2020-11-21 06:32 UTC, anuraaga approved these changes

2020-11-21 13:57 UTC, merged