Bump GCP dependencies to v0.35.2 and v1.11.2
open-telemetry/opentelemetry-collector-contrib pull request #18755
Opened 2023-02-17 14:30 UTC by damemi

**Description:** Updates GCP dependencies to pull in bug fixes

**Link to tracking Issue:** n/a

**Testing:** downstream unit+integration tests

**Documentation:** https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/releases/tag/v0.35.2

2023-02-17 14:40 UTC, dashpole approved these changes

2023-02-17 15:55 UTC, codeboten reviewed
Thanks @damemi, please run make crosslink

```
--- a/exporter/googlemanagedprometheusexporter/go.mod
+++ b/exporter/googlemanagedprometheusexporter/go.mod
@@ -93,3 +93,7 @@ require (
 )
 
 retract v0.65.0
+
+replace github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus => ../../pkg/translator/prometheus
+
+replace github.com/open-telemetry/opentelemetry-collector-contrib/internal/common => ../../internal/common
Replace statements are out of date, please run "make crosslink" and commit the changes in this PR.
```

2023-02-20 10:29 UTC, mx-psi commented on .chloggen/gcp-0-35-2.yaml
> +subtext: Fixes infinite loop/memory leak in GCP logging exporter. Also updates credentials config options.
Why not put this directly on the `note`? If you read the changelog you will know that this is a bugfix already because of the `change_type`.

2023-02-21 14:19 UTC, damemi commented
@codeboten thanks, updated

2023-02-23 18:01 UTC, codeboten requested changes
I'm not seeing anything else in this PR other than the changelog, please take a look.

2023-02-23 18:04 UTC, dashpole commented
I think it might've been beaten to it by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18825

2023-02-23 18:27 UTC, damemi commented
Yup, David's right, looks like the bump was pulled in by dependabot already. Closing this

2023-02-23 18:27 UTC, closed without merging