Support kafka-exporter synchronous and asynchronous sending
open-telemetry/opentelemetry-collector-contrib pull request #18774
Opened 2023-02-20 17:06 UTC by chenhaipeng

**Description:** In logs and traces scenarios, kafka asynchronous sending has a very good throughput, so I added a sendType feature, which uses sync sending by default

2023-02-23 00:08 UTC, MovieStoreGuy requested changes
There is a few things that I would like fixed up here.

2023-02-23 00:08 UTC, MovieStoreGuy commented on exporter/kafkaexporter/kafka_exporter.go
> +	}
Testing if `k` is nil here feels like an anti pattern and could lead to issues trying to diagnose problems with the `AsyncKafkaProducer`. It should panic if these aren't correctly set in the worst case (in the best case, return an error on creation).

2023-02-23 00:08 UTC, MovieStoreGuy commented on exporter/kafkaexporter/kafka_exporter.go
> +//func newSaramaProducer(config Config) (sarama.SyncProducer, error) {
Please don't add commented out code, please just remove it if it isn't needed.

2023-02-23 03:26 UTC, chenhaipeng commented on exporter/kafkaexporter/kafka_exporter.go
> +		fmt.Println("kafka SendType error please choose sync or async")
i will take a look, later

2023-02-24 08:00 UTC, chenhaipeng commented
> There is a few things that I would like fixed up here.

hi ,please take a look again ,thanks!

2023-05-31 03:16 UTC, chenhaipeng commented on exporter/kafkaexporter/kafka_exporter.go
> +		fmt.Println("kafka SendType error please choose sync or async")
Hi MovieStoreGuy, I have fixed all problems please look again

2023-06-29 05:20 UTC, closed without merging