[processor/spanmetrics] Deprecate spanmetrics processor.
open-telemetry/opentelemetry-collector-contrib pull request #19751
Opened 2023-03-16 15:21 UTC by kovrus

**Description:** <Describe what has changed.>

Deprecate the spanmetrics processor in favor of the spanmetrics connector.

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19736

**Documentation:** <Describe the documentation added.>
`spanmetrics` processor readme.

2023-03-16 15:31 UTC, kovrus commented
cc: @albertteoh

2023-03-16 16:33 UTC, djaglowski commented
@kovrus, the stability level is also defined in code [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/cd146d550ac893312aa03fc9c7e6534804606498/processor/spanmetricsprocessor/factory.go#L31). We should update that as well.

2023-03-17 07:12 UTC, albertteoh approved these changes

2023-03-17 07:12 UTC, albertteoh commented on .chloggen/spanmetrics-deprecate-processor.yaml
> +note: Deprecate the `spanmetrics` processor in favour if the `spanmetrics` connector.
```suggestion
note: Deprecate the `spanmetrics` processor in favour of the `spanmetrics` connector.
```

2023-03-17 10:24 UTC, mx-psi requested changes
We should also deprecate the go module, see https://go.dev/ref/mod#go-mod-file-module-deprecation

2023-03-17 11:59 UTC, mx-psi approved these changes

2023-03-17 13:01 UTC, atoulme approved these changes

2023-03-17 18:53 UTC, merged