[receiver/file] enable the receiver
open-telemetry/opentelemetry-collector-contrib pull request #20440
Opened 2023-03-28 22:34 UTC by pmcollins

**Description:** This change enables the file receiver, which is still in development, but can already be used to replay JSON metrics.

**Link to tracking Issue:** #14638

**Testing:** Manually tested in a simple pipeline.

**Documentation:** README had already been added.

2023-04-07 21:26 UTC, atoulme commented
FWIW changes look good to me. Please rebase and mark ready for review, and I'll be happy to approve?

2023-04-20 20:52 UTC, hughesjj requested changes
LGTM but we should be using `v0.75` right?

2023-05-09 12:53 UTC, pmcollins commented on cmd/otelcontribcol/go.mod
> +	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filereceiver v0.74.0
Done. Thanks.

2023-05-09 14:08 UTC, mx-psi commented on cmd/otelcontribcol/builder-config.yaml
> +  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filereceiver v0.75.0
```suggestion
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filereceiver v0.76.3
```

2023-05-09 16:51 UTC, pmcollins commented on cmd/otelcontribcol/builder-config.yaml
> +  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filereceiver v0.75.0
Thanks, Pablo. Should be fixed now.

2023-05-10 08:41 UTC, mx-psi approved these changes
Looks good to me, but there are some conflicts that need fixing

2023-05-10 16:15 UTC, merged