[chore] update usage of env var
open-telemetry/opentelemetry-collector-contrib pull request #20737
Opened 2023-04-06 18:28 UTC by codeboten

Fixes #17299

2023-04-06 18:29 UTC, codeboten commented
Pinging @mx-psi as this is mostly a redo of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17546

2023-04-10 11:27 UTC, mx-psi requested changes
Thanks :) There are a couple of missing docs/examples to update:
```
❯ rg --glob '!{*.sh,Dockerfile,Makefile}' '\$\{[^\{:]+?\}'

# Excluding some false positives from this output

processor/k8sattributesprocessor/testdata/e2e/collector/configmap.yaml
52:            endpoint: ${MY_POD_IP}:4317

extension/basicauthextension/README.md
41:        ${BASIC_AUTH_USERNAME}:${BASIC_AUTH_PASSWORD}

extension/observer/k8sobserver/README.md
58:This spec-determined value would then be available via the `${K8S_NODE_NAME}` usage in the observer configuration.

extension/observer/k8sobserver/config.go
38:	// Then set this value to ${K8S_NODE_NAME} in the configuration.

exporter/datadogexporter/examples/collector.yaml
98:    # endpoint: ${GATEWAY_HOST_IP}:4317

```

2023-04-21 08:45 UTC, codeboten reviewed
Updated, please take a look @mx-psi

2023-04-21 11:54 UTC, mx-psi approved these changes

2023-04-21 11:54 UTC, merged