[receiver/purefa] Some endpoints were not being scraped. This new code snippet, should resolve the bug.
open-telemetry/opentelemetry-collector-contrib pull request #21100
Opened 2023-04-21 16:15 UTC by dgoscn

**Description:**
Some endpoints from Pure Flash Array Receiver were not being scraped: **array**, **pods**, and **directories**.
The reason for that could be caused by a missing pattern insertion on the **volumes** scraper endpoint. This snippet code comes to fix this.

**Link to tracking Issue:**
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14886

**Testing:**
The validation test must be made by the default configs on config.yaml that is present on README.md.

**Documentation:**
Present on README

2023-04-21 17:06 UTC, chrroberts-pure requested changes

2023-04-21 17:17 UTC, dgoscn commented on receiver/purefareceiver/receiver.go
> +		"host":          model.LabelValue(r.cfg.Endpoint),
Excellent point, @chrroberts-pure. I will make the update, validate the tests and commit the changes right now.

Thanks

2023-04-28 14:47 UTC, james-laing commented
Issue #21248 describes the issue this PR is addressing.

2023-05-03 13:38 UTC, jpkrohling requested changes
I would like to see tests for this change, asserting the final state of the metrics and their labels. It's then easier to see what exactly is going on.

2023-05-03 13:38 UTC, jpkrohling commented on receiver/purefareceiver/receiver.go
> -		"deployment.environment": model.LabelValue(r.cfg.Env),
I'm curious as to why this is being changed. As it was, this was compliant with the semantic conventions, and this change breaks this.

2023-05-04 21:05 UTC, james-laing commented
Confirmed fix for Issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21248

2023-05-31 18:44 UTC, jpkrohling approved these changes
I'm approving, as PureStorage folks have tested and confirmed this to work. The new functional test is coming on a follow-up PR.

2023-05-31 18:46 UTC, merged