Azuremonitorreceiver: Option to add resource tags to metric attributes
open-telemetry/opentelemetry-collector-contrib pull request #21175
Opened 2023-04-25 19:41 UTC by rajim17

**Adding a feature:**
Resource/Service in the azure platform have tags in the form of key/value pairs . These tags can give additional information about the service like environment/name and other labels which can be useful to slice/dice the metrics. Resource also have location key which can also be added to metric attributes.

Adding tags to attributes can be optional. if users are interested , it can be enabled via config

**Link to tracking Issue:**  21173

**Testing:**  Added new tests 

**Documentation:**

2023-04-25 20:13 UTC, altuner requested changes
Small changes requested

2023-04-25 20:46 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
> +						if s.cfg.AppendTagsAsAttributes {
> what are the benefits of having this flag? Why not to get those values by default??

Want to give the flexibility to opt as more number of tags will increase the cardinality in downstream systems.

2023-04-25 20:48 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
> +						if s.cfg.AppendTagsAsAttributes {
> otherwise should we have a separate flag for location?

location can be also added as default if it is non-empty. share your opinion.

2023-04-26 18:21 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
> +						if s.cfg.AppendTagsAsAttributes {
@altuner - I added location as default. Tags are added based on config.

2023-04-26 18:37 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
> +						if len(res.location) > 0 {
@altuner - that's a good point. how about "tags_"  ??

2023-05-01 18:50 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
> +							attributes[tagPrefix+location] = &res.location
thanks @altuner. so below is the format.
metadata keys -> metadata_<> 
tag keys -> tags_<>
location -> location

2023-05-01 18:52 UTC, rajim17 commented on receiver/azuremonitorreceiver/testdata/expected_metrics/metrics_golden.yaml
> +                    - key: metadata_dimension
with prefixing, 
metadata keys will be `metadata_<key>` , hence changed in golden copy as well.

2023-05-01 19:10 UTC, altuner approved these changes
LGTM

2023-05-02 17:59 UTC, rajim17 commented
@codeboten - Could you review the changes ?

2023-05-02 19:41 UTC, codeboten approved these changes

2023-05-03 17:15 UTC, rajim17 commented
@codeboten - May I know the next steps in  merging to main ?

2023-05-04 15:12 UTC, codeboten commented
> @codeboten - May I know the next steps in merging to main ?

I was just waiting for the checks to pass yesterday :)

2023-05-04 15:13 UTC, merged