issue-21715 fetching metric values with composite(all) dimension keys
open-telemetry/opentelemetry-collector-contrib pull request #21716
Opened 2023-05-09 20:31 UTC by rajim17

**Description:**

If metric has multiple dimensions, metricValues are fetched by single dimension instead of combining all dimensions. With single dimension metric value is average value of other dimensions.

In below example without all dimensions in the filter, 'metadata_nodepool' provides average value of 2 'metadata_node' datapoints. But cannot combine dimensions of metadata_node under 'metadata_nodepool' dimensions.

```
Metric #44
Descriptor:
     -> Name: azure_node_cpu_usage_millicores_total
NumberDataPoints #0
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_nodepool: Str(general1)
Value: 625.500000

NumberDataPoints #1
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_node: Str(aks-general1-vmss00006x)
Value: 506.000000

NumberDataPoints #2
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_node: Str(aks-general1-vmss000062)
Value: 745.000000
```
With all Dimensions applied:
Here each datapoint provides all related dimension values. With this information, it is easy to apply multiple filters.

```
Metric #44
Descriptor:
     -> Name: azure_node_cpu_usage_millicores_total

NumberDataPoints #0
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_node: Str(aks-general1-vmss00006x)
     -> metadata_nodepool: Str(general1)
Value: 506.000000

NumberDataPoints #1
Data point attributes:
     -> azuremonitor.resource_id: Str(/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue)
     -> metadata_node: Str(aks-general1-vmss000062)
     -> metadata_nodepool: Str(general1)
Value: 745.000000
```

In Azuremonitor receiver, [getResourceMetricsValuesRequestOptions](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/azuremonitorreceiver/scraper.go#L372-L374) func, single dimension key alone provided. Instead all possible dimension keys for the metric have to be given. 
Solution:
    with metricresource definitions,  Generate hash string with all dimensions and store the metrics based on hash instead of single dimension + timegrain filter.

Sample MetricClient REST Request with all dimensions in filter:

`https://management.azure.com/subscriptions/test/resourceGroups/aks-dev2-blue/providers/Microsoft.ContainerService/managedClusters/aks-dev2-blue/providers/Microsoft.Insights/metrics?timespan=2023-04-29T02:20:00Z/2023-05-04T04:20:00Z&interval=PT1H&api-version=2018-01-01&metricnamespace=Microsoft.ContainerService/managedClusters&metricnames=node_cpu_usage_millicores&$filter=nodepool eq '*' and node eq '*'`

**Link to tracking Issue:** 21715

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

2023-05-12 14:51 UTC, rajim17 commented
@altuner @codeboten - Could you help review the changes ?

2023-05-16 20:24 UTC, altuner requested changes
left small comments

2023-05-16 23:32 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
>  type metricsCompositeKey struct {
Yes. I removed metricsCompositeKey struct and directly injecting into azureResourceMetrics.

2023-05-18 17:32 UTC, altuner approved these changes
LGTM

2023-05-18 17:49 UTC, altuner requested changes

2023-05-18 18:22 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
> +	metricsByCompositeKey     map[string]*azureResourceMetrics
@altuner - dimensions is slice in type metricsCompositeKey hence can't be used as a key in map. Have to use hash string as key. I can revert to previous commit keeping metricsCompositeKey and still using it's hash string as key to map.

2023-05-19 03:52 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
> +	metricsByCompositeKey     map[string]*azureResourceMetrics
I'm not sure of any other way other than hashing to store the key to map. Yes, I should add sort to make sure dimension strings are ordered.  Let me add that. Do you think metricsCompositeKey struct can be useful ?

2023-05-19 23:46 UTC, rajim17 commented on receiver/azuremonitorreceiver/scraper.go
> +	metricsByCompositeKey     map[string]*azureResourceMetrics
that is a very good idea. I just changed to comma separated strings and used compositeKey as key in the map.

2023-05-23 18:05 UTC, rajim17 commented
> @rajim17 please fix the breaking test

Integration_test on rabbitmqreceiver  was failing. I triggered the build process with dummy commit message and tests are running. I will check once build is complete.

2023-05-23 18:28 UTC, rajim17 commented
@altuner - All tests are passed.

2023-05-23 23:19 UTC, altuner approved these changes

2023-05-24 17:19 UTC, rajim17 commented
@codeboten - Could you help reviewing the PR ?

2023-05-26 17:15 UTC, junhuangli commented
@altuner We are waiting for this fix. Could you merge this pull request or is there anything still pending?

2023-05-30 17:59 UTC, rajim17 commented
@codeboten - Could you help merging this PR ? It is already approved by code owner @altuner .

2023-06-01 19:43 UTC, junhuangli commented
@codeboten Could you take another look at this PR :)

2023-06-02 19:43 UTC, codeboten approved these changes

2023-06-02 19:44 UTC, merged