[prometheusreceiver] enable reporting of additional metrics issue #21064
open-telemetry/opentelemetry-collector-contrib pull request #21763
Opened 2023-05-10 16:28 UTC by premendrasingh

Feature: Enable reporting of additional metrics for Prometheus client used in PrometheusReceiver

**Description:**
Prometheus client has a featureFlag options.ExtraMetrics which reports content size metric ([scrape_body_size_bytes](https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L1770)) for successful scrapes and -1 for dropped data. This metric will help us collect data and setup alert for dropped data. However the prometheus receiver does not have a way to enable this feature flag.

This PR passes the flag to scrape.NewManager() to enable reporting of metric - [scrape_body_size_bytes](https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L1770)

**Link to tracking Issue:**
#21040 

**Testing:**
Added check for validating the value set in testdata/config.yaml

2023-06-01 22:22 UTC, premendrasingh commented
@JaredTan95, @dashpole 
CLA is signed, please help review this PR. 
Thanks.

2023-06-02 06:16 UTC, JaredTan95 commented
thx your contribution, But could you add some tests to cover your enhanced or the scraped results if `report_extra_metrics` is true. :-P

2023-06-02 06:18 UTC, JaredTan95 requested changes
thx your contribution, But could you add some tests to cover your enhanced or the scraped results if `report_extra_metrics` is true?  :-P

2023-06-21 18:03 UTC, dashpole reviewed
lgtm overall.  Just one suggestion

2023-06-21 18:03 UTC, dashpole commented on receiver/prometheusreceiver/testdata/config.yaml
> +  report_extra_metrics: true
I would suggest including "scrape" in the name, as it is a scrape.Option.  Possibly "report_extra_scrape_metrics".

2023-06-26 02:06 UTC, premendrasingh commented
Thanks @JaredTan95 @dashpole for the suggestions. Added test case and changed name to `report_extra_scrape_metrics`

2023-06-26 13:04 UTC, dashpole approved these changes

2023-07-10 05:56 UTC, premendrasingh commented
@JaredTan95  @Aneurysm9 @dashpole I have added change log. Please help review. Thanks.

2023-07-10 06:02 UTC, JaredTan95 commented
> @JaredTan95 @Aneurysm9 @dashpole I have added change log. Please help review. Thanks.

great, and last thing, we should update the `README.md` docs for describing `report_extra_scrape_metrics` .

2023-07-10 06:28 UTC, premendrasingh commented
@JaredTan95  Updated README.md

2023-07-10 06:36 UTC, JaredTan95 commented on receiver/prometheusreceiver/README.md
> +- `receiver.prometheusreceiver.report_extra_scrape_metrics`: Extra prometheus scrape metrics can be reported by setting this parameter to `true`
```suggestion
- `report_extra_scrape_metrics`: Extra Prometheus scrape metrics can be reported by setting this parameter to `true`
```

2023-07-10 06:39 UTC, premendrasingh commented on receiver/prometheusreceiver/README.md
> +- `receiver.prometheusreceiver.report_extra_scrape_metrics`: Extra prometheus scrape metrics can be reported by setting this parameter to `true`
Thanks for the suggestion.

2023-07-10 06:42 UTC, JaredTan95 approved these changes
LGTM

@Aneurysm9 pls take a look

2023-08-01 14:57 UTC, merged

2023-08-01 18:11 UTC, premendrasingh commented
Thanks @JaredTan95, @dashpole, @mx-psi for helping with the PR merge process.