[receiver/datadog] add datadog span and trace id
open-telemetry/opentelemetry-collector-contrib pull request #23058
Opened 2023-06-05 06:28 UTC by povilasv

**Description:** <Describe what has changed.>

Add datadog trace id and span id so we cancorrelate traces received by datadogreceiver with logs.

Datadog libraries automatically provide datadog span ids and trace ids with the logs for various languages:

- https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/python/
-https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/java?tab=log4j2

Example log for python:
```
2023-06-05 06:01:30,459 INFO [__main__] [test-enhanced.py:44] [dd.service= dd.env= dd.version= dd.trace_id=6249785623524942554 dd.span_id=2
28114450199004348] - Starting a new Game!
```

**Link to tracking Issue:**  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23057
**Testing:** <Describe what testing was performed and which tests were added.>
- local testing with python app
- updated unit tests
- 
**Documentation:** <Describe the documentation added.>

2023-06-11 07:47 UTC, boostchicken requested changes

2023-06-11 07:47 UTC, boostchicken commented on receiver/datadogreceiver/translator.go
> +			newSpan.Attributes().PutStr("datadog.span.id", strconv.FormatUint(span.SpanID, 10))
I would be nice to have these strings in an enum like semconv.  DD changes these all the time and I suspect that there will be many changes like this in the future.  Why not make a data structure to hold these strings and then loop over it dynamically? That way in the future we can just add a new entry to the enum.

2023-06-13 13:28 UTC, MovieStoreGuy commented
Can I ask what are you trying to visualise this data in? Is there any reason why you can't use the trace ID and span ID that is already sent?

I don't believe adding span field to an attribute is a good idea, it is wasteful since it is duplicating data.

2023-07-10 19:58 UTC, jpkrohling commented
> Since datadog library give log in this format:

Aren't those trace IDs and span IDs the same as already set a few lines above?

2023-07-26 19:44 UTC, jpkrohling commented
ping @povilasv

2023-07-27 17:50 UTC, jpkrohling commented
@boostchicken , @MovieStoreGuy , can you take another look at this one?

2023-07-27 23:22 UTC, boostchicken commented
> @boostchicken , @MovieStoreGuy , can you take another look at this one? 

Sure thing

2023-07-28 13:14 UTC, MovieStoreGuy approved these changes
I understand why this is needed but ideally I would like to see this work be done by a connector in a more generic sense

2023-08-04 18:15 UTC, jpkrohling commented
I'm merging this as it's only about adding two new attributes. If @boostchicken has concerns, we can revert or work on this on a follow-up PR.

2023-08-04 18:15 UTC, merged

2023-08-04 18:34 UTC, boostchicken commented
No major concerns fine as is, my feedback was more a matter of opinion than best practice :)

2024-02-01 20:11 UTC, clintonb commented
I recognize I'm late to the party, but what was the goal of this change? It makes sense to add the `dd.trace_id` and `dd.span_id` attributes to _logs_. What's the point of adding them to traces and spans? What is using these `datadog.*` attributes?