feat(alertmanager): Add exporter implementation
open-telemetry/opentelemetry-collector-contrib pull request #23604
Opened 2023-06-21 12:30 UTC by mcube8

**Description:** Implementation of Alertmanager Exporter
Span Events are exported to Prometheus Alertmanager 

**Link to tracking Issue:** [#23659 ](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23569)

**Testing:** Unit tests for config, factory and alertmanager exporter implementation

**Documentation:** Readme and Sample Configs to use Alertmanager exporter

2023-06-21 13:11 UTC, mx-psi requested changes
This component does not have a sponsor yet, blocking until we have a sponsor.

The PR would also need to be split, and CLA signed, but let's figure out the sponsor situation first.

2023-06-21 14:16 UTC, sandy2008 approved these changes

2023-06-22 06:19 UTC, mcube8 commented
/easycla

2023-06-22 06:26 UTC, sokoide commented
/easycla

2023-07-22 05:19 UTC, closed without merging