Use `Available` memory instead of `Free` to compute system.memory.usage:free
open-telemetry/opentelemetry-collector-contrib pull request #24033
Opened 2023-07-07 13:46 UTC by ItsLastDay

**Description:** Fixes a bug where `system.memory.usage:free` has strange values

**Link to tracking Issue:** [<Issue number if applicable>](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24031)

**Testing:** Not yet tested

**Documentation:** nothing added. What should I add?

2023-07-18 22:45 UTC, crobert-1 commented
You'll need to add a [changelog entry](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-a-changelog-entry) for this change since this will have user impact.

2023-07-18 22:48 UTC, crobert-1 approved these changes
From the [documentation you referenced](https://github.com/shirou/gopsutil/blob/v3.23.6/mem/mem.go#L34-L37) it looks like this is the right variable to use.

It would be really good to have a comparison before and after the change to confirm that the new metric being used is what's expected, and charts (like you shared in your original issue) make sense with the new values.

2023-07-19 06:42 UTC, dmitryax commented
Please look at this issue first https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417 . I don't believe we agreed on this solution. The work on that issue got stuck, but there is a System semantic conventions WG started recently, so it's a good chance to come to a solution finally. Please feel free to join https://github.com/open-telemetry/opentelemetry-specification/issues/3556. There are weekly calls on Web 8:30 AM PST.

2023-07-19 06:43 UTC, dmitryax requested changes
^

2023-08-03 07:47 UTC, ItsLastDay commented
Thank you Dmitrii for information! I'll close this PR and my issue, and will continue in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7417.

I see that Braydon (who's also from Google) expressed interest in helping with #7417 in https://github.com/open-telemetry/opentelemetry-specification/issues/3556#issuecomment-1642338045. So I hope I'll personally be able to skip the WG meetings, and instead provide all the context asynchronously through comments.

2023-08-03 07:47 UTC, closed without merging