Azure monitor workload identity
open-telemetry/opentelemetry-collector-contrib pull request #24543
Opened 2023-07-25 12:40 UTC by cmergenthaler

**Description:** 
Enhances azuremonitor receiver authentication by using [azure workload identity](https://azure.github.io/azure-workload-identity/docs/). I have added a new config parameter `auth` to specify the used authentication method (default set to service-principal) in order to possibly add more methods in the future.

**Link to tracking Issue:** Fixes #24451 

**Testing:** Tested on my AKS

**Documentation:** Added to README.md

2023-07-26 10:47 UTC, fatsheep9146 reviewed
since the service_principal and workload_identity are both used in multiple places, how about convert them into consts?

2023-07-26 12:12 UTC, cmergenthaler commented
> since the service_principal and workload_identity are both used in multiple places, how about convert them into consts?

Good point! I have converted them to be consts

2023-07-26 14:05 UTC, fatsheep9146 approved these changes

2023-08-01 17:39 UTC, altuner requested changes
Good job with improving the receiver, I've added few small comments

2023-08-02 06:18 UTC, cmergenthaler commented on receiver/azuremonitorreceiver/README.md
> +- `AZURE_TENANT_ID`
Thanks for the hint, I have adjusted to inputs

2023-08-02 06:18 UTC, cmergenthaler commented on receiver/azuremonitorreceiver/scraper.go
> +	switch s.cfg.Authentication {
Done

2023-08-02 07:24 UTC, fatsheep9146 commented
@cmergenthaler please fix the failed test, thanks

2023-08-14 10:09 UTC, cmergenthaler commented
> @cmergenthaler please fix the failed test, thanks

@fatsheep9146 done

2023-08-29 05:24 UTC, altuner approved these changes

2023-09-05 07:41 UTC, cmergenthaler commented
Anything missing here? Would be nice to have this merged so that I don't have to rebase and resolve conflicts again.

2023-09-08 22:48 UTC, codeboten reviewed
Thanks for the contribution, just a comment re. constants that don't need to be public. Otherwise it looks good

2023-09-08 22:48 UTC, codeboten commented on receiver/azuremonitorreceiver/config.go
> +	WorkloadIdentity = "workload_identity"
These don't need to be public

```suggestion
	servicePrincipal = "service_principal"
	workloadIdentity = "workload_identity"
```

2023-09-11 05:57 UTC, cmergenthaler commented on receiver/azuremonitorreceiver/config.go
> +	WorkloadIdentity = "workload_identity"
thanks for the hint, updated the consts

2023-09-19 17:09 UTC, codeboten reviewed
@cmergenthaler please resolve the last conflict and we can get this merged

2023-09-27 06:23 UTC, cmergenthaler commented
> @cmergenthaler please resolve the last conflict and we can get this merged

@codeboten done, please merge

2023-09-27 17:48 UTC, codeboten approved these changes

2023-09-27 17:48 UTC, codeboten commented
Thanks @cmergenthaler!

2023-09-27 17:48 UTC, merged