Change type.pod to type == "pod" in Receiver Creator config rules
open-telemetry/opentelemetry-collector-contrib pull request #2661
Opened 2021-03-11 23:00 UTC by bjsignalfx

**Description:** Change from using **type.pod** to use **type == "pod"** in Receiver Creator configuration rule expressions.

**Testing:** Fixed unit tests failing due to change 

**Documentation:** Updated documentation to reflect change.

2021-03-12 23:54 UTC, bogdandrutu commented
/cc @jrcamp

2021-03-17 18:36 UTC, tigrannajaryan commented
@jrcamp please review.

2021-03-17 21:06 UTC, jrcamp requested changes

2021-03-17 21:06 UTC, jrcamp commented on receiver/receivercreator/rules.go
> +var ruleRe = regexp.MustCompile(`^type(\s*==\s*"pod"|\.port)`)
While you're there can you also add "hostport", was missing.

2021-03-17 21:06 UTC, jrcamp commented on extension/observer/endpoints.go
> +	if e.Details.Type() == PodType {
Should go ahead and change all types in one PR.

2021-03-17 21:06 UTC, jrcamp commented on receiver/receivercreator/README.md
> +`type`
This doesn't provide the necessary context anymore. `type: "pod"` maybe?

2021-03-17 21:06 UTC, jrcamp commented on receiver/receivercreator/README.md
> +| type        | `pod`                            |
```suggestion
| type        | `"pod"`                            |
```

2021-03-23 14:30 UTC, tigrannajaryan commented
Please resolve merge conflict.

2021-03-23 21:28 UTC, jrcamp approved these changes

2021-03-23 22:00 UTC, merged