[receiver/azuremonitor]: Support Azure gov cloud
open-telemetry/opentelemetry-collector-contrib pull request #27573
Opened 2023-10-10 01:18 UTC by danelson

**Description:** <Describe what has changed.>
Support Azure gov cloud

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** Ran against a government subscription

**Documentation:** Updated README

2023-10-10 01:21 UTC, danelson commented on receiver/azuremonitorreceiver/config.go
> +	azureCloud           = "AzureCloud"
I am not sure these are the preferred names, but these are the names returned from running `az cloud list`. Other tools use different conventions (e.g. terraform).

2023-10-26 21:02 UTC, danelson commented
@codeboten @altuner can I get some feedback on this?

2023-10-26 21:27 UTC, altuner requested changes

2023-10-26 22:08 UTC, danelson commented on receiver/azuremonitorreceiver/README.md
> +    cloud: AzureUSGovernment
Not sure. I wouldn't expect users to include this line at all when configuring the public cloud. They can also infer this from the bullets above but I thought a more complete example was nice. Happy to use the default tho if you think that makes sense.

2023-10-26 22:10 UTC, danelson commented on receiver/azuremonitorreceiver/factory.go
> +	defaultCloud              = "AzureCloud"
Had to move config vars to constants. Let me know if that doesn't work

2023-11-07 01:06 UTC, danelson commented on receiver/azuremonitorreceiver/README.md
> +    cloud: AzureUSGovernment
@altuner just following up here and with the other changes.

2023-11-15 18:01 UTC, danelson commented
@altuner @codeboten sorry to keep pinging but I would love to move this along so that I can use it in my collector. Anything I can do to make that happen please let me know!

2023-11-16 22:07 UTC, codeboten approved these changes

2023-11-16 22:56 UTC, codeboten reviewed
See the suggestion

```
        	            	type "Config" from package "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azuremonitorreceiver" has invalid config settings: field "Cloud" has config tag "" which doesn't satisfy "^[a-z0-9][a-z0-9_]*$"
```

2023-11-16 22:56 UTC, codeboten commented on receiver/azuremonitorreceiver/config.go
> +	Cloud                                   string                        `mapstructure:",cloud"`
```suggestion
	Cloud                                   string                        `mapstructure:"cloud"`
```

2023-11-17 17:31 UTC, merged