remove deprecated container.cpu.utilization metric
open-telemetry/opentelemetry-collector-contrib pull request #27795
Opened 2023-10-17 06:34 UTC by sigilioso

**Description:** <Describe what has changed.>

Following up #24183, this PR removes the deprecated `container.cpu.percent` metric as explained in README's [deprecation section](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/dockerstatsreceiver#transition-to-cpu-utilization-metric-name-aligned-with-opentelemetry-specification).

**Link to tracking Issue:** #21807

**Testing:** <Describe what testing was performed and which tests were added.>

```
❯ go test -race -timeout 300s -parallel 4 --tags="" ./... -count 1
ok      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver  1.480s
ok      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver/internal/metadata        1.525s
```

**Documentation:** the documentation has been updated using `mdatagen`

2023-10-17 08:18 UTC, mx-psi reviewed
The PR title should talk about `cpu.container.percent` instead, shouldn't it?

2023-10-17 08:18 UTC, mx-psi commented on .chloggen/remove-deprecated-cpu-metric.yaml
> +change_type: deprecation
We already deprecated this metric, this is a breaking change:

```suggestion
change_type: breaking
```

2023-10-17 09:02 UTC, mx-psi approved these changes

2023-10-17 09:02 UTC, sigilioso commented
> The PR title should talk about `cpu.container.percent` instead, shouldn't it?

I forgot to edit the PR title 🤦, thanks for pointing it out.  I've just changed it.

2023-10-18 23:00 UTC, dmitryax commented
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24183 has not been released yet. Please update the schedule in readme in a separate PR. We should hold off on merging this one until 0.88.0 is released

2023-10-18 23:01 UTC, dmitryax requested changes
LGTM but we need to hold off until 0.88.0 is released

2023-10-19 06:52 UTC, sigilioso commented
The schedule has just been updated in #27853 andI will rebase this when it is merged. Thanks for clarifying!

2023-10-26 03:16 UTC, dmitryax approved these changes

2023-10-26 03:16 UTC, merged