Have consumer spans name follow service name attribute
open-telemetry/opentelemetry-collector-contrib pull request #29564
Opened 2023-11-29 17:44 UTC by atshaw43

**Description:** <Describe what has changed.>
Kafka consumer spans are not leveraging the service name for their span names.

**Link to tracking Issue:**
https://github.com/aws-observability/aws-otel-collector/issues/894

**Testing:**
Unit tests

2023-11-30 03:07 UTC, bryan-aguilar commented on exporter/awsxrayexporter/internal/translator/segment.go
>  		// Only for a server span, we can use the resource.
This comment should probably be updated also

2023-11-30 03:18 UTC, bryan-aguilar requested changes

2023-11-30 03:18 UTC, bryan-aguilar commented on exporter/awsxrayexporter/internal/translator/segment_test.go
> +	span := constructServerSpan(parentSpanID, spanName, 0, "OK", attributes)
You are constructing a server span here and not a consumer span. The unit test should be updated to reflect the functionality under test.

2023-11-30 18:17 UTC, bryan-aguilar approved these changes

2023-12-04 15:16 UTC, songy23 approved these changes

2023-12-18 19:33 UTC, evan-bradley commented
@wangzlei @srprash could you please take a look as code owners?

2024-01-02 19:14 UTC, evan-bradley commented
@wangzlei @srprash Please take a look.

2024-02-02 05:19 UTC, closed without merging