[chore] make addlicense consistent
open-telemetry/opentelemetry-collector-contrib pull request #29873
Opened 2023-12-13 23:38 UTC by hughesjj

**Description:** Fixes divergence in add/check license
**Link to tracking Issue:** Resolves #29863

**Testing:**
After this changefix, the reproduction in upstream issue will produce the following output

```
❯ echo '#!/bin/bash' >> receiver/redisreceiver/testdata/integration/will_fail_checklicense.sh
make addlicense
make checklicense
Add License finished successfully
Check License finished successfully
❯ git status
On branch fix_addlicense
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        receiver/redisreceiver/testdata/integration/will_fail_checklicense.sh

nothing added to commit but untracked files present (use "git add" to track)
```

2023-12-14 00:09 UTC, crobert-1 requested changes

2023-12-14 00:09 UTC, crobert-1 commented on Makefile.Common
> +                                -not -path '*/local/*' \
I noticed `local/` wasn't originally ignored, but found it's in [`.gitignore`,](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/615aad997ab60a8123d5660d61497fce67f16948/.gitignore#L1) so there's no point in including it in makefile logic.

(I agree with your change here, just pointing out why)

2023-12-14 00:09 UTC, crobert-1 commented on Makefile.Common
> +                                -not -path '*/third_party/*' \
```suggestion
                                -not -path '**/third_party/*' \
```
We may want to keep the same regex here for `third_party` directories, it looks like the `**` originally there allows crossing directory boundaries, so any `third_party` sub-directory would be ignored, not just the top level. [Relevant link](https://stackoverflow.com/questions/46547540/meaning-of-a-double-star-in-a-file-path). Let me know if I'm missing something here.

2023-12-14 00:19 UTC, crobert-1 commented
For the sake of complete testing, could you compare the list of files returned by the original `checklicense` `find` command, and the new one? You'd probably have to sort the old one (the new one's sorted) to get them to match, but it would be good to ensure at this point there's no change to `checklicense`. You don't have to share the complete lists, but if you could just confirm they match it would be good.

2023-12-14 00:29 UTC, crobert-1 commented
> Link to tracking Issue: [29863]

One more thing for now, could you change the above line in your description to be:
```
Link to tracking issue:
Resolves #29863
```
This will allow GitHub to link and automatically close the issue when the PR is resolved.

2023-12-14 00:31 UTC, crobert-1 commented on Makefile.Common
> +                                -not -path '*/third_party/*' \
Fair point, I missed that this was consistent with other references in the makefile. In that case, it's fine with me to leave it for now, but I'll defer to others if there are more concerns here. 👍

2023-12-20 16:23 UTC, crobert-1 approved these changes

2023-12-20 16:23 UTC, crobert-1 commented on Makefile.Common
> +
```suggestion
```

2023-12-21 23:32 UTC, atoulme approved these changes

2024-01-18 23:02 UTC, pjanotti approved these changes

2024-01-24 21:01 UTC, merged