[chore] move opensearch exporter to generated lifecycle tests
open-telemetry/opentelemetry-collector-contrib pull request #30476
Opened 2024-01-12 11:30 UTC by JaredTan95

Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27849

2024-01-12 15:50 UTC, codeboten approved these changes

2024-01-12 15:51 UTC, codeboten requested changes
Looks like the lifecycle tests are failing:

```

            	            	Permanent error: Permanent error: flush: dial tcp: lookup opensearch.example.com on 127.0.0.53:53: no such host
            	            	Permanent error: Permanent error: flush: dial tcp: lookup opensearch.example.com on 127.0.0.53:53: no such host
```

2024-01-13 02:20 UTC, JaredTan95 commented
> Looks like the lifecycle tests are failing:
> 
> ```
> 
>             	            	Permanent error: Permanent error: flush: dial tcp: lookup opensearch.example.com on 127.0.0.53:53: no such host
>             	            	Permanent error: Permanent error: flush: dial tcp: lookup opensearch.example.com on 127.0.0.53:53: no such host
> ```

The `opensearch exporter` `endpoint` in config must be not be empty and requires an address to receive the consumed traces data, so we'll skip the error checking by `expect_consumer_error: true` for now

2024-01-17 21:54 UTC, codeboten approved these changes

2024-01-17 21:54 UTC, merged