Add scale_value transformation
open-telemetry/opentelemetry-collector-contrib pull request #3177
Opened 2021-04-20 04:36 UTC by quentinmit

**Description:** <Describe what has changed.>

Adds a "scale_value" transformation that can be used to change values' units or otherwise scale them.

**Link to tracking Issue:** <Issue number if applicable>
None

**Testing:** <Describe what testing was performed and which tests were added.>
Unit tests and example config included as part of the PR

**Documentation:** <Describe the documentation added.>
Example usage documented in the README.md

2021-04-22 20:17 UTC, punya approved these changes
The first line of the README should also be changed to reflect the new capability.

2021-04-22 20:18 UTC, punya commented on processor/metricstransformprocessor/operation_scale_value.go
> +// Copyright 2020 OpenTelemetry Authors
Nit: Newly added files should use 2021 as the copyright year.

2021-04-30 07:13 UTC, quentinmit commented
This PR is still active and is awaiting review.

2021-05-04 19:48 UTC, djaglowski approved these changes
LGTM (Please fix lint though)

2021-05-11 21:30 UTC, quentinmit commented
I think I fixed the lint error and comments.

It sounds like you might prefer naming this `experimental_`, so I added a separate commit to rename this if that would make it more likely to merge this.

2021-05-19 07:08 UTC, quentinmit commented
Still not stale.

2021-05-19 17:41 UTC, tigrannajaryan requested changes, later dismissed
The functionality looks useful but we need to decide where it lives. It intersects with https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2722

https://github.com/open-telemetry/opentelemetry-collector/issues/3185 is an open issue that aims to find a good overall structure for processors.

I am temporarily blocking this until we figure out what is the right way forward and the right processor to put this in.

@bogdandrutu if you had discussed this earlier and had a resolution please comment.

2021-05-19 18:09 UTC, jrcamp commented
@tigrannajaryan @bogdandrutu Given that it's going to probably be a while until a new metrics processor can be designed and implemented maybe we should take relatively trivial improvements to this processor in the meantime? (Obviously 'trivial' will then be debatable but I would say this falls into that bucket)

2021-05-19 21:31 UTC, bogdandrutu commented
@punya I am ok to merge this if you sign to do the work of transforming this processor to pdata :)

2021-05-19 21:33 UTC, punya commented
@bogdandrutu that helps, let me discuss with the team and get back on that in the next couple of days.

2021-05-24 16:45 UTC, punya commented
@bogdandrutu @quentinmit this is still on my radar, I had to take off for a bit because of family issues.

2021-05-24 16:58 UTC, punya commented
@bogdandrutu the Google team is signing up to do the work to convert this from OC to OTel data types. Please merge this PR in the meantime.

2021-05-26 17:19 UTC, qingling128 commented
@bogdandrutu - Anything else we need to address before this PR could be merged?

2021-05-26 17:21 UTC, qingling128 commented
Ah, looks like it needs to be rebased. @quentinmit - Could you help with that?

2021-06-01 10:32 UTC, quentinmit commented
I just force-pushed this PR with a rebased patchset on top of current `main`.

2021-06-03 17:17 UTC, qingling128 commented
Hi @bogdandrutu @tigrannajaryan - Anything else we need to do before this could be merged? All the tests seem to pass. Previous comment / feedback have been addressed. And Google is signing up to do the work to convert this from OC to OTel data types.

CC @punya for visibility

2021-06-03 23:38 UTC, sophieyfang commented
This is currently blocking to adjust our three metrics that we want to go GA with. Now those are in 1/1000th.

agent.googleapis.com/disk/weighted_io_time
agent.googleapis.com/disk/{io,operation}_time

2021-06-08 22:58 UTC, tigrannajaryan commented
> @punya I am ok to merge this if you sign to do the work of transforming this processor to pdata :)

> @bogdandrutu the Google team is signing up to do the work to convert this from OC to OTel data types. Please merge this PR in the meantime.

@bogdandrutu do you have any other concerns or good to merge?

2021-06-08 22:59 UTC, tigrannajaryan approved these changes

2021-06-09 16:29 UTC, merged