Allow customers to set custom resource attributes as container Tags
open-telemetry/opentelemetry-collector-contrib pull request #32224
Opened 2024-04-08 17:57 UTC by dineshg13

**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

2024-04-08 18:26 UTC, songy23 approved these changes
LGTM except minor nits

2024-04-08 18:53 UTC, jdgumz commented on connector/datadogconnector/connector_test.go
> +	assert.ElementsMatch(t, []string{"region:my-region", "zone:my-zone", "az:my-az"}, tags)
👍

2024-04-09 10:09 UTC, mx-psi requested changes

2024-04-09 10:09 UTC, mx-psi commented on .chloggen/dinesh.gurumurthy_expand-resource-attributes.yaml
> +  This change allows the connector to use any attribute from the resource as a container tag. This is useful when you want to use a custom attribute from the resource as a container tag. For example,
The last part is unnecessary: if it were a breaking change then the `change_type` would be `breaking`, not `enhancement`.
```suggestion
  This change allows the connector to use any attribute from the resource as a container tag. This is useful when you want to use a custom attribute from the resource as a container tag. For example, you can use the `namespace` attribute from the resource as a container tag.
```

2024-04-09 10:09 UTC, mx-psi commented on .chloggen/dinesh.gurumurthy_expand-resource-attributes.yaml
> +component: datadog/connetor
```suggestion
component: datadog/connector
```

2024-04-09 10:09 UTC, mx-psi commented on .chloggen/dinesh.gurumurthy_expand-resource-attributes.yaml
> +note: Enable connetor to use any attribute from the resource as Container Tag
```suggestion
note: Enable connector to use any attribute from the resource as Container Tag
```

2024-04-09 10:09 UTC, mx-psi commented on connector/datadogconnector/connector.go
> +		}
We have full control over the `attributes` package, we don't need to resort to hacks, we can just file a PR over there. I can merge this PR tomorrow morning if that PR has not landed, but I will wait until the PR is open

2024-04-09 19:03 UTC, songy23 approved these changes
LGTM

2024-04-10 08:21 UTC, mx-psi approved these changes

2024-04-10 10:55 UTC, merged