[receiver/hostmetrics] Add documentation for mute_*_error configuration fields
open-telemetry/opentelemetry-collector-contrib pull request #32494
Opened 2024-04-17 18:46 UTC by bsponge

**Description:**
Added documentation for mute_*_error configuration fields and updated comments in the code.

**Link to tracking Issue:** 30779

**Testing:** not applicable

**Documentation:** Added missing documentation of mute_*_error configuration in hostmetricsreceiver

2024-04-17 18:58 UTC, braydonk requested changes
Hi @bsponge, thanks for opening a PR for this!

Unfortunately, the documentation can't be added where you have it here; note at the top of that file that it mentions it is autogenerated and thus shouldn't be edited.

What I'd suggest instead is adding it to the `README.md` in the root `hostmetricsreceiver` folder. In there, you'll see a section that shows the configuration options for every scraper. This can definitely be improved, but for now if you could add those descriptions directly below the `yaml` example that would be good for now. 

The rest of the PR looks good to me.

2024-04-17 19:09 UTC, braydonk approved these changes
Thanks, looks good to me! Will still need approval from dmitryax before merge.

2024-04-17 19:34 UTC, crobert-1 approved these changes
Thanks for your PR, always appreciate documentation enhancements!

2024-04-17 19:35 UTC, crobert-1 commented
_Hope you don't mind, I updated your PR description to [automatically close the linked issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#description-guidelines)_ 👍

2024-04-17 19:36 UTC, bsponge commented on .chloggen/add-mute-error-documentation.yaml
done

2024-05-02 12:18 UTC, braydonk commented
unstale

2024-07-17 15:48 UTC, rogercoll commented
Could we reopen this PR? This is still important documentation we should have in the `process` scrapper.

2024-07-17 21:41 UTC, crobert-1 commented
_Added `ready to merge` as it's been approved by an approver and code owner._

2024-07-17 22:31 UTC, braydonk commented
@crobert-1 Maybe you'll know the answer to this. I'm not sure if as a codeowner in `.github/CODEOWNERS` my approval is supposed to count for codeowner approval according to GitHub (still has the grey checkmark here and in other PRs). This has been the case for a while but I wasn't sure if it was intentional or not, if I mixed something up with adding myself as a codeowner I can try to fix it.

2024-07-17 23:13 UTC, crobert-1 commented
> @crobert-1 Maybe you'll know the answer to this. I'm not sure if as a codeowner in `.github/CODEOWNERS` my approval is supposed to count for codeowner approval according to GitHub (still has the grey checkmark here and in other PRs). This has been the case for a while but I wasn't sure if it was intentional or not, if I mixed something up with adding myself as a codeowner I can try to fix it.

It's nothing wrong on your side, the green check mark is reserved for approvers and maintainers of the project, unrelated to code owners. Code owners are automatically added as reviewers on PRs, and we can also manually check the `.github/CODEOWNERS` file to see if someone is a code owner for a given component. (For reference, [here's a recent PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34063) where code owner approved and they also don't have a green check mark, just to confirm it's not you.)

I see you also requested a review from @dmitryax, but given this is only a documentation change, I assume we're good to merge. Is that accurate, or would you still prefer a review?

2024-07-18 13:30 UTC, braydonk commented
Thanks for the clarification; I was used to other repos where approvals from CODEOWNERS were green check so I wasn't sure.

I thought merging would be blocked by Dmitrii's review; if it wouldn't be, then I imagine this is fine to merge.

2024-07-18 15:37 UTC, crobert-1 commented
> I thought merging would be blocked by Dmitrii's review; if it wouldn't be, then I imagine this is fine to merge.

One code owner approval is just fine by default, especially for something simple like this that's only documentation. That being said, if you're ever unsure about a change or want specific feedback from another code owner we can definitely block and ask for more input 👍

2024-07-22 14:21 UTC, codeboten approved these changes

2024-07-22 14:22 UTC, merged