Double the number of exporter build-and-test groups
open-telemetry/opentelemetry-collector-contrib pull request #32496
Opened 2024-04-17 20:53 UTC by jmacd

**Description:** Double the number of exporter test groups so that new tests can be added, e.g., the new tests in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31996.

**Testing:** These changes were applied in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31996 and they resolved a timeout.

2024-04-17 21:03 UTC, songy23 approved these changes

2024-04-17 21:13 UTC, crobert-1 approved these changes

2024-04-17 21:13 UTC, crobert-1 commented on Makefile
> +EXPORTER_MODS_0 := $(shell find ./exporter/[a-c]* $(FIND_MOD_ARGS) -exec $(TO_MOD_DIR) )
Just a note for context, this split ends up being the following number of exporters in each group:

Group 0: 13
Group 1: 10
Group 2: 8
Group 3: 12

<details>
<summary>Here's the full split, if anyone's interested </summary>
<br>

 ```
./exporter/alertmanagerexporter
./exporter/alibabacloudlogserviceexporter
./exporter/awscloudwatchlogsexporter
./exporter/awsemfexporter
./exporter/awskinesisexporter
./exporter/awss3exporter
./exporter/awsxrayexporter
./exporter/azuredataexplorerexporter
./exporter/azuremonitorexporter
./exporter/carbonexporter
./exporter/clickhouseexporter
./exporter/cassandraexporter
./exporter/coralogixexporter

./exporter/datadogexporter
./exporter/datasetexporter
./exporter/elasticsearchexporter
./exporter/fileexporter
./exporter/googlecloudexporter
./exporter/googlecloudpubsubexporter
./exporter/googlemanagedprometheusexporter
./exporter/honeycombmarkerexporter
./exporter/influxdbexporter
./exporter/instanaexporter

./exporter/kafkaexporter
./exporter/loadbalancingexporter
./exporter/logicmonitorexporter
./exporter/logzioexporter
./exporter/lokiexporter
./exporter/mezmoexporter
./exporter/opencensusexporter
./exporter/opensearchexporter

./exporter/prometheusexporter
./exporter/prometheusremotewriteexporter
./exporter/pulsarexporter
./exporter/sapmexporter
./exporter/sentryexporter
./exporter/signalfxexporter
./exporter/skywalkingexporter
./exporter/splunkhecexporter
./exporter/sumologicexporter
./exporter/syslogexporter
./exporter/tencentcloudlogserviceexporter
./exporter/zipkinexporter
```

</details>

Given how uneven the distribution is in component names, I think this is as good of a split as possible with the current set of exporters. 👍

2024-04-17 21:15 UTC, crobert-1 commented
_Failing test is frequency of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27295, I've added it as frequency there._

2024-04-18 13:33 UTC, songy23 reviewed
Can you update `.github/workflows/build-and-test-windows.yml` as well?

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32510 for context. cc @mx-psi

2024-04-18 14:01 UTC, dashpole approved these changes

2024-04-18 15:12 UTC, crobert-1 requested changes
I just realized you'll also need to update `build-and-test-windows.yml` with the new exporter groups.

2024-04-18 15:44 UTC, jmacd commented
Oh! The windows build-and-test appears out-of-date prior to my change--apparently was skipping some receiver tests.
See [feb5ba2](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32496/commits/feb5ba249ca134273b38482b76e06d4093c13b79)

2024-04-18 15:48 UTC, crobert-1 commented
> Oh! The windows build-and-test appears out-of-date prior to my change--apparently was skipping some receiver tests. See [feb5ba2](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32496/commits/feb5ba249ca134273b38482b76e06d4093c13b79)

You're right, we're fixing it in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32518, which is what made me remember this would need updated too. 👍 

If possible, maybe only add the new groups to the Windows tests, and let the other PR add the rest? That way the changelog will be a bit more clear going forward.

2024-04-18 17:55 UTC, crobert-1 approved these changes
Thanks for making the extra changes!

2024-04-22 22:17 UTC, jmacd commented
```
=== Errors
multiple definitions of TestMain
```

2024-04-22 22:26 UTC, crobert-1 commented
> ```
> === Errors
> multiple definitions of TestMain
> ```

Should be fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32603. Hopefully another rebase should fix it.

2024-04-23 10:13 UTC, merged