[processor/remotetap] Fix memory leak on shutdown
open-telemetry/opentelemetry-collector-contrib pull request #32571
Opened 2024-04-19 22:03 UTC by crobert-1

**Description:** <Describe what has changed.>

The remotetap processor holds a map of channels for writing telemetry data to WebSockets when a client connects. The write process works by blocking on a given channel waiting for telemetry data coming through the processor's pipeline, then writing as soon as it comes in. This however can result in a leaked goroutine that blocks forever if data is not received, which is always the case when shutting down.

This fixes the bug by closing and deleting all channels once all client connections have been shutdown gracefully. This fixes the blocking behavior during shutdown.

This change also enables `goleak` to help ensure no goroutines are being leaked.

**Link to tracking Issue:** <Issue number if applicable>
#30438

**Testing:** <Describe what testing was performed and which tests were added.>
All existing tests are passing, as well as added `goleak` check.

2024-04-19 22:04 UTC, crobert-1 commented on .chloggen/goleak_remotetap.yaml
> +issues: []
```suggestion
issues: [32571]
```

2024-04-19 22:48 UTC, atoulme approved these changes

2024-04-19 23:33 UTC, songy23 approved these changes

2024-04-23 17:55 UTC, codeboten requested changes

2024-04-23 17:55 UTC, codeboten commented on processor/remotetapprocessor/metadata.yaml
> +    skip: false
the goleak section can be removed completely here

2024-04-23 18:07 UTC, crobert-1 commented on processor/remotetapprocessor/metadata.yaml
> +    skip: false
```suggestion
```

2024-04-23 18:12 UTC, codeboten commented on processor/remotetapprocessor/metadata.yaml
>    goleak:
This can be removed as well :)

2024-04-23 18:25 UTC, crobert-1 commented on processor/remotetapprocessor/metadata.yaml
>    goleak:
🤦 Done

2024-04-24 14:03 UTC, codeboten approved these changes

2024-04-24 14:03 UTC, merged