[chore][processor/remotetap] fix component name in README
open-telemetry/opentelemetry-collector-contrib pull request #32582
Opened 2024-04-21 16:41 UTC by andrzej-stencel

2024-04-21 19:12 UTC, atoulme approved these changes

2024-04-23 16:16 UTC, codeboten approved these changes

2024-04-23 16:16 UTC, codeboten requested changes

2024-05-06 20:31 UTC, andrzej-stencel commented on processor/remotetapprocessor/README.md
> +    port: 12001
That's correct. I've rebased this PR on the most recent changes.

2024-05-07 15:37 UTC, codeboten approved these changes

2024-05-07 15:37 UTC, merged