[exporter/datadog]: improve mappings for span kind dd span type
open-telemetry/opentelemetry-collector-contrib pull request #3368
Opened 2021-05-11 08:59 UTC by ericmustin

**Description:** <Describe what has changed.>

This PR Adds some additional mappings between opentelemetry span kind and datadog span type, that allow users to see more specialized UIs and representation of traces properly marked `db` or `cache` whereas previously they were all `custom`

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.> updated unit tests

**Documentation:** <Describe the documentation added.>

2021-05-11 15:23 UTC, mx-psi requested changes

2021-05-12 02:49 UTC, ericmustin commented on exporter/datadogexporter/translate_traces.go
> +	kindMemcached       string = "memcached"
sounds good, made a pr here https://github.com/open-telemetry/opentelemetry-specification/pull/1689

2021-05-12 13:53 UTC, ericmustin commented on exporter/datadogexporter/translate_traces.go
> +		if dbSysOtlp, okDbSysOtlp := datadogTags[conventions.AttributeDBSystem]; okDbSysOtlp {
updated

2021-05-12 13:54 UTC, ericmustin commented on exporter/datadogexporter/translate_traces_test.go
> +	assert.Equal(t, "cache", spanTypeCache)
updated

2021-05-12 13:54 UTC, ericmustin commented on exporter/datadogexporter/translate_traces_test.go
> +		"db.system": "postgres",
updated

2021-05-12 14:00 UTC, mx-psi approved these changes

2021-05-12 15:55 UTC, merged