add cadvisor for container insight receiver
open-telemetry/opentelemetry-collector-contrib pull request #3414
Opened 2021-05-17 22:19 UTC by pxaws

**Description:** <Describe what has changed.>
Add cadvisor for container insight receiver
* embed cadvisor lib inside and use it collect container stats
* generate metrics based on container stats

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2307

**Testing:** <Describe what testing was performed and which tests were added.>
Unit tests.

2021-05-17 22:41 UTC, pxaws commented
@alolita @mxiamxia

2021-05-18 22:13 UTC, Aneurysm9 requested changes

2021-05-26 02:32 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/container_info_processor_test.go
> +// }
I will remove them.

2021-05-26 04:59 UTC, anuraaga approved these changes

2021-05-26 04:59 UTC, anuraaga commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +		err := errors.New("missing environment variable HOST_NAME. Please check your deployment YAML config")
Can we return the err?

2021-05-26 05:05 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
>  // TODO: add proper field for Cadvisor
yes, it is removed in the latest change.

2021-05-26 05:23 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +		err := errors.New("missing environment variable HOST_NAME. Please check your deployment YAML config")
Sure. I will make the change.

2021-06-01 21:19 UTC, mxiamxia approved these changes

2021-06-02 23:57 UTC, pxaws commented
The checks failed at `loadtest` which shouldn't be caused by current code changes. I will `git push -f` to re-trigger the checks.

2021-06-04 21:16 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +	return manager.New(memoryCache, sysfs, houskeepingConfig, includedMetricsSet, collectorHTTPClient, rawContainerCgroupPathPrefixWhiteList, perfEventsFile)
Talked with Aneurysm9 offline and explained the reason for the code. As suggested by Aneurysm9, I added comments to explain the code.

2021-06-04 22:21 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +		if f := flag.Lookup(name); f != nil {
Right. The flag overriding should be done in `init()`. I have made the change. As for whether we should changing `flag` in the current way (like what kubelet did), I will do more research and put info here.

2021-06-04 23:46 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +		if f := flag.Lookup(name); f != nil {
It seems like the flag `housekeeping_interval ` that we are overriding is only used in one place: https://github.com/google/cadvisor/search?q=%22housekeeping_interval%22&type=code. The value is taken directly from commandline flag: https://github.com/google/cadvisor/blob/ef7e64f9efab1257e297d7af339e94bb016cf221/manager/container.go#L49
I see the value is used in a couple of places:
* https://github.com/google/cadvisor/blob/ef7e64f9efab1257e297d7af339e94bb016cf221/manager/container.go#L525-L526
* https://github.com/google/cadvisor/blob/ef7e64f9efab1257e297d7af339e94bb016cf221/manager/container.go#L441
* https://github.com/google/cadvisor/blob/ef7e64f9efab1257e297d7af339e94bb016cf221/manager/container.go#L498-L500

I don't think cadvisor currently provide a way to customize the flag value through any api. So overriding the flag value seems to be the only way to change the default. Maybe that's the reason that kubelet code is doing the same thing.

2021-06-04 23:47 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +		if f := flag.Lookup(name); f != nil {
@bogdandrutu @tigrannajaryan Please take a look and let us know if it is OK for us to merge the code like this. Thank you very much!

2021-06-07 20:41 UTC, dashpole commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +		if f := flag.Lookup(name); f != nil {
I would suggest not overriding cAdvisor flags, and instead opening a PR against cAdvisor to make it explicitly configurable.  I'm happy to approve such PRs.  The kubelet probably shouldn't be doing that either...

2021-06-07 21:29 UTC, dashpole commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +		if f := flag.Lookup(name); f != nil {
But since that will take a while, it is probably acceptable to do this for now if they need to have this configuration.

2021-06-09 17:11 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
> +		if f := flag.Lookup(name); f != nil {
I changed the code to override the variable `HousekeepingInterval` from cadvisor manager package. This is a little hacky but is much better than overriding the global flags. I will need to use the proper way once the cadvisor issue is resolved: https://github.com/google/cadvisor/issues/2886

2021-06-09 17:12 UTC, Aneurysm9 approved these changes

2021-06-11 05:55 UTC, bogdandrutu commented
@alolita @anuraaga @Aneurysm9 it is very hard (impossible) to review 7K line PRs especially when I don't know if some of the code is copied, etc. I don't know how you did this, but I have 0 confidence about merging this change.  Let me know how you did this, otherwise I think we should split the PR into a PR that copies the code (if that is the case) and second PR that uses the code.

2021-06-11 05:56 UTC, bogdandrutu commented
Removed ready-to-merge since this is way above the size of a reviewable PR

2021-06-14 10:45 UTC, bogdandrutu commented
Still ~2.5K PR, needs to be split

2021-06-14 16:12 UTC, pxaws commented
> Still ~2.5K PR, needs to be split

I am going to split the current PR further, but they will need to base on the PR for adding the test json files: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3756. Could you merge that PR first? Thanks

2021-06-15 23:45 UTC, pxaws commented
@bogdandrutu I have separated some code into a different PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3790. Could you merge it? Thanks! (I will sent another PR after that PR is merged and then I will modify the current PR to reduce the size)

2021-06-16 14:35 UTC, tigrannajaryan commented
> @bogdandrutu I have separated some code into a different PR: #3790. Could you merge it? Thanks! (I will sent another PR after that PR is merged and then I will modify the current PR to reduce the size)

@pxaws since you are submitting different PRs should we close this PR?

2021-06-16 16:38 UTC, pxaws commented
> > @bogdandrutu I have separated some code into a different PR: #3790. Could you merge it? Thanks! (I will sent another PR after that PR is merged and then I will modify the current PR to reduce the size)
> 
> @pxaws since you are submitting different PRs should we close this PR?

Sure. You can close this PR.

2021-06-17 16:34 UTC, closed without merging