[exporter/clickhouse] Use the standard default of 10 queue consumers
open-telemetry/opentelemetry-collector-contrib pull request #34176
Opened 2024-07-19 18:35 UTC by tommyzli

**Description:** 
The default number of [queue consumers is in the exporter helper 10](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/queue_sender.go#L45). This default is respected by every other exporter in this repo except for the ClickHouse exporter. A default of 1 is way too low for any major workload and adds a low ceiling to the vertical scalability of a single collector.

**Link to tracking Issue:** n/a

**Testing:** n/a

**Documentation:** Added the default values to the README

2024-07-19 20:45 UTC, SpencerTorres requested changes
Good find, we just need to add a changelog entry. Appreciate the contribution!

2024-07-19 21:21 UTC, SpencerTorres approved these changes

2024-07-19 22:30 UTC, crobert-1 approved these changes

2024-07-26 15:30 UTC, merged

2024-07-26 23:58 UTC, cwegener commented
Huh. I thought I had raised an issue about this a long time ago and it had previously been resolved. Odd.

2024-07-28 01:14 UTC, cwegener commented
Hmm .. Ok. Maybe I should have made top-level issue for it instead.
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28579#issuecomment-1784759475

Good that it's now fixed.