[exporter/datadog] Remove deprecated peer_service_aggregation
open-telemetry/opentelemetry-collector-contrib pull request #34177
Opened 2024-07-19 19:21 UTC by songy23

Config `peer_service_aggregation` has been deprecated in favor of `peer_tags_aggregation` since v0.89

2024-07-20 20:18 UTC, dineshg13 approved these changes

2024-07-22 08:12 UTC, mx-psi requested changes
Can we add this to removed settings? https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/dba8f51f2576fbdd877b6c1839176c83ff0be4b3/exporter/datadogexporter/config.go#L546

2024-07-22 13:29 UTC, songy23 commented
Added to removedSettings

2024-07-24 14:50 UTC, songy23 commented
Discussed in another PR, going to put this PR on hold for now.

2025-01-24 01:34 UTC, MovieStoreGuy commented
Hey @songy23 ,

Is there still a need for this PR?

2025-01-24 04:26 UTC, songy23 commented
This is not needed right now, I can close. When this is needed it can be reopened.

2025-01-24 04:26 UTC, closed without merging