[chore] Create configuration to enable development in this repository using Project IDX
open-telemetry/opentelemetry-collector-contrib pull request #34405
Opened 2024-08-05 06:51 UTC by michaelsafyan

**Description:**

Specifies the necessary `.idx/...` config so that this repository (or forks of this repository) can easily be edited in IDX.

**Purpose**

Increase development velocity.

**Background:**

[Project IDX](https://idx.dev/) is a Cloud-based IDE from Google. It provides for a hermetic, reproducible development environment using [NixOS](https://nixos.org/) configuration to define environment dependencies. Development with Project IDX requires a `.idx/dev.nix` configuration to define the requires libraries, binaries, packages, services, etc.

For more info, see:

 - https://developers.google.com/idx

2024-08-05 08:27 UTC, mx-psi requested changes
Hey, thanks for your contribution! While I understand how this may be useful for you and other folks using IDX, it would be hard for us to maintain this, since (AFAIK) none of the maintainers use it. We could improve this with some sort of CI check, but still we need to justify that this is used.

I would suggest something like this:
- File a PR that adds `.idx/` to `.gitignore`, so that you and other users can add their own configuration comfortably
- File an issue to gauge interest through upvotes to add this and close this PR for now

2024-08-05 08:48 UTC, michaelsafyan commented
Putting it in `.gitignore` and reverting is not ideal for several reasons:

 1. Creating a correct `.idx/dev.nix` takes time.
 2. Different versions of `.idx/dev.nix` defeats the main benefit of a reproducible/repeatable environment.
 3. A copy is needed in each branch, adding work effort/friction to usage.
 4. That solution would also preclude ["Open in IDX"](https://developers.google.com/idx/guides/open-in-idx).

If no one ends up using IDX for development with this repository, then it is also of no consequence if it breaks; breakage in the configuration here would only affect those developing in this repository using IDX; it would not negatively impact those making use of the components provided in this repository. Worst-case scenario: it breaks, and then the next person who wants to use it with IDX would notice that it doesn't work and would need to fix it.

2024-08-05 09:09 UTC, mx-psi commented
I understand that `.gitignore` is not ideal, but this is something that requires no maintenance from our side and solves at least one problem (that of needing to remove this folder before commiting). Adding this to `.gitignore` does not mean we can't eventually add `.idx` to our codebase if enough people want it and we know how to maintain it.

I still don't think it's a good idea to commit something that we don't know how to maintain. We (maintainers, approvers) won't be able to address issues raised about it, which is one of the responsibilities assumed of us.

If, after opening an issue, this gains enough traction, then we can consider it, but right now we don't have a good idea of how many people this would be useful to.

cc @open-telemetry/collector-approvers to chime in in case you disagree with this assessment

2024-08-05 16:42 UTC, atoulme commented on .idx/dev.nix
> +    CGO_ENABLED = 1;
We don't allow CGO for the collector right now.

2024-08-06 01:50 UTC, michaelsafyan commented
At head, "make test" fails without this flag, which suggests that one of
the components in the repository is using this setting.

On Mon, Aug 5, 2024, 11:42 AM Antoine Toulme ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In .idx/dev.nix
> <https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34405#discussion_r1704386553>
> :
>
> > +
> +  # Use https://search.nixos.org/packages to find packages
> +  packages = [
> +    pkgs.go
> +    pkgs.gnumake
> +    pkgs.gcc
> +    pkgs.docker
> +    # pkgs.python311
> +    # pkgs.python311Packages.pip
> +    # pkgs.nodejs_20
> +    # pkgs.nodePackages.nodemon
> +  ];
> +
> +  # Sets environment variables in the workspace
> +  env = {
> +    CGO_ENABLED = 1;
>
> We don't allow CGO for the collector right now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34405#pullrequestreview-2219450984>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABI65JMT4YSWKBEPKKDCRTZP6TQNAVCNFSM6AAAAABL7U7XTOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMJZGQ2TAOJYGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <open-telemetry/opentelemetry-collector-contrib/pull/34405/review/2219450984
> @github.com>
>

2024-08-06 08:25 UTC, mx-psi commented
> At head, "make test" fails without this flag, which suggests that one of the components in the repository is using this setting.

This is likely because the race detector we use on tests needs cgo. But on actual builds we forbid cgo entirely

2024-08-07 02:35 UTC, TylerHelmuth requested changes
I agree that we should not merge this. The repository should not start taking on IDE-specific files as we won't be able to validate them or how they'll interact with other IDEs.

2024-08-07 06:18 UTC, michaelsafyan commented
Thanks for the feedback.

I have sent a separate pull request to add `.idx/` to `.gitignore`:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34457

2024-08-07 06:22 UTC, michaelsafyan commented
Given that there are now two expressions of concern regarding submitting such a config, would it still be useful/productive to create "an issue to gauge interest through upvotes" as initially suggested? Or is that a lost cause?

2024-08-07 09:39 UTC, mx-psi commented
> Given that there are now two expressions of concern regarding submitting such a config, would it still be useful/productive to create "an issue to gauge interest through upvotes" as initially suggested? Or is that a lost cause?

We would need a significant number of people to express a need/desire for this, as well as a plan on how we can maintain this before adding it. I personally would not outright discard the possibility if IDX becomes wildly popular in the future, but we can wait for @TylerHelmuth to give their opinion as well before filing the issue

2024-08-09 16:32 UTC, TylerHelmuth commented
Issue for discussion is fine.

2024-09-08 05:21 UTC, closed without merging