[connector/datadog] Move feature gate connector.datadogconnector.NativeIngest to beta
open-telemetry/opentelemetry-collector-contrib pull request #34549
Opened 2024-08-08 20:45 UTC by songy23

2024-08-08 20:46 UTC, songy23 commented on .chloggen/dd-conn-fg.yaml
> +issues: []
```suggestion
issues: [34549]
```

2024-08-09 04:55 UTC, dineshg13 approved these changes

2024-08-09 08:14 UTC, mx-psi requested changes
Can you add some brief explanation to the PR description?

2024-08-09 12:53 UTC, songy23 commented
> Can you add some brief explanation to the PR description?

Done

2024-08-09 12:55 UTC, mx-psi approved these changes

2024-08-09 12:55 UTC, merged