[opampsupervisor] add unit tests
open-telemetry/opentelemetry-collector-contrib pull request #34812
Opened 2024-08-22 12:34 UTC by bacherfl

**Description:** This PR adds more unit tests to the OpAmpSupervisor

**Link to tracking Issue:** #24295 

**Testing:** Added more unit tests to increase coverage

2024-08-27 15:51 UTC, atoulme commented on .chloggen/opamp-supervisor-unit-tests.yaml
> +note: Increase unit test coverage.
no need for a changelog for tests, we can skip changelog for those.

2024-09-26 14:10 UTC, BinaryFissionGames requested changes
Thanks for taking this on, sorry for the delay in review! It generally looks good to me, just a few small things.

2024-09-27 06:52 UTC, bacherfl commented
> Thanks for taking this on, sorry for the delay in review! It generally looks good to me, just a few small things.

No worries, and thanks a lot for the review! I have addressed all comments now (will keep an eye on the CI checks to make sure everything passes)

2024-09-27 06:53 UTC, bacherfl commented on cmd/opampsupervisor/supervisor/supervisor_test.go
> +			pidProvider: defaultPIDProvider{},
good idea, seems like I overlooked the `staticPIDProvider` - that definitely makes it a bit simpler

2024-10-03 11:28 UTC, bacherfl commented on cmd/opampsupervisor/supervisor/supervisor_test.go
> +	t.Run("EffectiveConfig - Effective config message does not contain instance config", func(t *testing.T) {
thanks for the suggestion, that sounds better

2024-10-03 11:29 UTC, bacherfl commented on cmd/opampsupervisor/supervisor/supervisor_test.go
> +		// replace the ppid as that changes with each run
that comment was a leftover from before where i did not use the static PPID provider yet. I removed that comment now as it's not required anymore

2024-10-03 15:17 UTC, evan-bradley approved these changes

2024-10-15 17:26 UTC, merged