k8sclusterreceiver: migrate to latest semconv version
open-telemetry/opentelemetry-collector-contrib pull request #35238
Opened 2024-09-17 10:38 UTC by narcis96

Description: The version of semconv is upgraded from to v1.18.0 to v1.27.0

Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22095

Testing: Tests passed

2024-09-17 16:03 UTC, TylerHelmuth requested changes
Upgrading semconv is risky. Please confirm that no metrics or attributes emitted by this component change bc of this upgrade.

2024-09-24 11:36 UTC, narcis96 commented
> Upgrading semconv is risky. Please confirm that no metrics or attributes emitted by this component change bc of this upgrade.

The semconv attributes' value have been compared using [go-otel-semconv-comparator](https://github.com/narcis96/go-otel-semconv-comparator) resulting in 0 diffs.

2024-10-02 09:34 UTC, narcis96 commented
hey guys, can you please take a look ? @dmitryax @povilasv @TylerHelmuth

2024-10-04 08:54 UTC, narcis96 commented
> Could you elaborate what your tools does? What did you compare? Where did you found no differences?

The tool checks that all constants from the older semconv version have the same value inside the newer semconv version.

2024-10-24 13:16 UTC, narcis96 commented
did my last question answered your question ? are there any concerns on this ? @dmitryax @TylerHelmuth @povilasv

2024-11-15 23:34 UTC, ChrsMark commented
Looked for which conventions are used in the component: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-collector-contrib+path%3Areceiver%2Fk8sclusterreceiver+conventions.&type=code&ref=advsearch

It appears that resource names and uids are used which I believe have not changed. @povilasv could you double check?

2024-12-01 19:51 UTC, dmitryax approved these changes
There should be no backward incompatible changes for this receiver afaik

2024-12-02 08:46 UTC, ChrsMark commented
@narcis96  could you rebase?

2024-12-05 17:32 UTC, TylerHelmuth approved these changes

2024-12-11 11:45 UTC, narcis96 commented
@ChrsMark done. PTAL

2024-12-16 18:05 UTC, ChrsMark approved these changes

2025-01-09 00:47 UTC, narcis96 commented
@povilasv PTAL

2025-01-09 08:29 UTC, ChrsMark reviewed
@narcis96  the failing tests look relevant? Could you take care of them?

2025-01-23 23:46 UTC, atoulme commented
Please update the golden files used in e2e tests.

2025-02-22 05:19 UTC, closed without merging