kubeletstatsreceiver: migrate to latest semconv version
open-telemetry/opentelemetry-collector-contrib pull request #35273
Opened 2024-09-18 11:49 UTC by narcis96

Description: The version of semconv is upgraded from v1.6.1 to v1.27.0

Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22095

Testing: Tests passed

2024-09-18 14:54 UTC, codeboten approved these changes

2024-09-18 15:06 UTC, ChrsMark reviewed
Sharing the same concern with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35238.

Such an upgrade of SemConv's version might be risky.

In addition we might need to think if we should target this upgrade now or postpone for when the K8s semantic conventions are stable (there is some work planned for this, starting soon). 

In any case if we are to apply this upgrade now it would be nice to verify which SemConv attributes this receiver uses and ensure that they are not changed from one version to the other.

2024-09-18 15:43 UTC, TylerHelmuth requested changes
Upgrading semconv is risky. Please confirm that no metrics or attributes emitted by this component change bc of this upgrade.

2024-09-18 15:58 UTC, codeboten reviewed
My search through this receiver was that only `container.id` was used, and it hasn't changed between the two versions

2024-09-19 11:33 UTC, ChrsMark commented
Thank's @codeboten! I can confirm it's only used at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e42da8b86ee446a384132bbfbda3b4d04be51ce5/receiver/kubeletstatsreceiver/internal/kubelet/metadata.go#L24. In that case we could do the upgrade now and close the gap for this receiver.
@TylerHelmuth wdyt?

2024-09-19 17:52 UTC, TylerHelmuth approved these changes

2024-09-19 20:08 UTC, ChrsMark approved these changes

2024-09-19 20:26 UTC, merged