[exporter/logzio] Use NewDefaultClientConfig instead of manually creating struct
open-telemetry/opentelemetry-collector-contrib pull request #35524
Opened 2024-10-01 13:17 UTC by mackjmr

**Description:**
This PR makes usage of `NewDefaultClientConfig` instead of manually creating the confighttp.ClientConfig struct.

**Link to tracking Issue:** #35457

2024-10-02 13:08 UTC, yotamloe requested changes
Looks good to me :) Please run `go mod tidy` to update `go.mod` since your change deprecates usage of `go.opentelemetry.io/collector/config/configopaque`

2024-10-08 07:45 UTC, yotamloe approved these changes
I'm approving, but we still need to update `go.mod` as I can see that the `project: tidy` workflow was skipped

2024-10-08 15:20 UTC, mackjmr commented
@yotamloe I ran make gotidy and this resulted in no changes

2024-10-09 11:50 UTC, andrzej-stencel approved these changes

2024-10-09 11:50 UTC, merged