fix api key validation issue when quotations are escaped inside string
open-telemetry/opentelemetry-collector-contrib pull request #36510
Opened 2024-11-22 21:22 UTC by jackgopack4

#### Description
strips unintentional quotations from API key string in `pkg/datadog` config

#### Link to tracking issue
Fixes #36509

#### Testing
existing unit test pipeline

#### Documentation
changelog file

2024-11-25 09:06 UTC, mx-psi commented
```
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -56,3 +56,3 @@
        	            	  API: (config.APIConfig) {
        	            	-  Key: (configopaque.String) "",
        	            	+  Key: (configopaque.String) (len=10) "[REDACTED]",
        	            	   Site: (string) (len=13) "datadoghq.com",
        	Test:       	TestUnmarshal/unmarshall_confighttp_client_configs
```

2024-11-25 14:42 UTC, jackgopack4 commented
> ```
>         	            	Diff:
>         	            	--- Expected
>         	            	+++ Actual
>         	            	@@ -56,3 +56,3 @@
>         	            	  API: (config.APIConfig) {
>         	            	-  Key: (configopaque.String) "",
>         	            	+  Key: (configopaque.String) (len=10) "[REDACTED]",
>         	            	   Site: (string) (len=13) "datadoghq.com",
>         	Test:       	TestUnmarshal/unmarshall_confighttp_client_configs
> ```

going to look into this, not clear immediately if it's just broken/outdated test or if my change broke the intended behavior

2024-11-25 15:51 UTC, jackgopack4 commented
there may still be a discussion to be had around if we need to improve our API Key validation logic, but this keeps the behavior of v0.110.0 and prior so as to not break existing customers

2024-11-26 09:18 UTC, mx-psi requested changes
This error comes from changes in the confmap and it is intentional. You can see the `"0123"` row in https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/rfcs/env-vars.md#comparison-table-with-current-behavior that is this very case. I think we should not do this change and just think about how to improve the user experience (I left a concrete suggestion below).

2024-11-26 16:35 UTC, jackgopack4 commented on pkg/datadog/config/config.go
> +	c.API.Key = configopaque.String(strings.Trim(string(c.API.Key), `"'`))
I have changed the approach to validate hex characters via regex

2024-11-27 20:18 UTC, jackgopack4 commented on pkg/datadog/config/config_test.go
> +			name: "invalid format api::key",
new invalid API character test

2024-12-02 17:24 UTC, jackgopack4 commented on pkg/datadog/config/config.go
> -	c.API.Key = configopaque.String(strings.TrimSpace(string(c.API.Key)))
this was unintentional; I think it was because I replaced this line in the initial attempt but didn't restore it when I changed my approach

2024-12-02 17:27 UTC, jackgopack4 commented on pkg/datadog/config/config.go
> +	nonHex := regexp.MustCompile("[^0-9a-fA-F]")
as in we might break someone who has a datadog api key that is an invalid format? Or as in there might be datadog api keys that don't fit this regex?

2024-12-02 17:31 UTC, mx-psi commented on pkg/datadog/config/config.go
> +	nonHex := regexp.MustCompile("[^0-9a-fA-F]")
> Or as in there might be datadog api keys that don't fit this regex?

I am worried about this one, the other one doesn't matter much IMO

2024-12-03 10:49 UTC, mx-psi approved these changes
LGTM, can you fix the merge conflicts so I can merge?

2024-12-03 15:37 UTC, jackgopack4 commented
@mx-psi fixed merged conflicts and failing tests, should be good to go

2024-12-04 09:42 UTC, merged