add darwin arm64 target
open-telemetry/opentelemetry-collector-contrib pull request #3664
Opened 2021-05-29 21:47 UTC by codeboten

**Description:** 
Adding a target to build darwin arm64 binary.

2021-05-30 12:40 UTC, owais approved these changes

2021-05-30 13:25 UTC, owais requested changes
Change looks fine but CI is failing to build the binary.

2021-05-30 22:18 UTC, codeboten commented
> Change looks fine but CI is failing to build the binary.

Thanks for the review, I haven't had chance to dig into it, will do this later on this week.

2021-06-01 16:52 UTC, gramidt approved these changes

2021-06-09 09:50 UTC, jpkrohling commented
@owais, could you please review this one again, please?

2021-06-09 13:54 UTC, owais approved these changes

2021-06-10 08:19 UTC, merged