Adding Manu Agrawal, manu2 as an owner
open-telemetry/opentelemetry-collector-contrib pull request #36664
Opened 2024-12-04 09:13 UTC by KiranmayiB

#### Description

#### Link to tracking issue
Fixes

#### Testing

#### Documentation

2024-12-04 09:38 UTC, mx-psi requested changes
Thanks for the PR! Per [the contributing guidelines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#requirements), @manu2 would first have to [be a member of the OpenTelemetry organization.](https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md#member)

2024-12-04 10:38 UTC, manu2 commented
> Thanks for the PR! Per [the contributing guidelines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#requirements), @manu2 would first have to [be a member of the OpenTelemetry organization.](https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md#member)

@mx-psi Have raised a membership request: https://github.com/open-telemetry/community/issues/2475.

2025-01-08 22:20 UTC, codeboten commented
@KiranmayiB can you take a look at the comments on the PR

2025-01-17 10:53 UTC, KiranmayiB commented
We are seething this error when running make gengithub

`2025/01/17 10:52:37 codeowners are not members: Erog38, Frapschen, IbraheemA, JonathanWamsley, MovieStoreGuy, Mrod1598, NassimBtk, RichieSams, StefanKurek, VihasMakwana, adrielp, ag-ramachandran, akats7, alexvanboxel, ankitpatel96, antonblock, armstrmi, atingchen, atoulme, avadhut123pisal, bertysentry, braydonk, bryan-aguilar, carsonip, chan-tim-sumo, chrroberts-pure, codeboten, cparkins, cpheps, dashpole, dehaansa, dgoscn, edmocosta, eedorenko, erichsueh3, evan-bradley, fatsheep9146, fchikwekwe, gjanco, greatestusername, hughesjj, jacobmarble, jade-guiton-dd, jamesmoessis, jaronoff97, jmacd, joker-star-l, jsuereth, kasia-kujawa, khyatigandhi6, kongluoxing, liustanley, lquerel, manu2, mapno, mar4uk, marctc, martin-majlis-s1, mcardy, michalpristas, moh-osman3, mrsillydog, narcis96, nslaughter, pavankrish123, pcwiese, pjanotti, portertech, povilasv, psx95, pxaws, qiansheng91, rapphil, rnishtala-sumo, rogercoll, samiura, schmikei, shabicheng, shalper2, sinkingpoint, smithclay, splunkericl, srprash, tamir-michaeli, tomaz-s1, wangzlei, yotamloe, zdaratom-s1
make: *** [Makefile:319: gengithub] Error 1
`

Can you please suggest what we should do? @atoulme @codeboten

2025-01-17 22:38 UTC, atoulme commented
You are not an opentelemetry member and therefore do not have access to the list of members when performing the check.

You can run `gengithub --skipgithub` to avoid running into this problem.

2025-03-02 05:20 UTC, closed without merging

2025-03-03 05:51 UTC, atoulme commented
@KiranmayiB please let us know if this PR should be reopened? @manu2 please chime in as well

2025-05-06 09:53 UTC, manu2 commented
@atoulme I am creating a PR for adding myself to codeowner and moving the inactive members to emeritus. however on running `make gengithub` or ` make update-codeowners` I get the following errors:

`2025/05/06 09:40:10 codeowners members duplicate in allowlist: Caleb-Hurshman, adcharre, cheempz, dlopes7, jcreixell, jerrytfleung, joker-star-l, jriguera, michael-burt, rlankfo, thmshmm
`

None of the above mentioned users are part of the googlecloudspannerreceiver component. What is the guidance to fix this error? Could not find anything on this in the guidance docs.