[pkg/stanza] Log the entry in `HandleEntryError` when the transformer on_error mode is send_quiet or drop_quiet
open-telemetry/opentelemetry-collector-contrib pull request #36899
Opened 2024-12-19 07:57 UTC by namco1992

#### Description

The `HandleEntryError` is used in many places for handling parsing errors. Sometimes the error itself is not very helpful, e.g. the syslog parser return errors like "parsing error [col 66]", which is quite hard to understand without seeing the actual entry.

This PR logs the entry when the error mode is `send_quiet` or `drop_quiet` in debug level. It shouldn't add too much noise and could be very helpful in debugging.

2024-12-20 15:03 UTC, djaglowski requested changes
I don't agree that quiet mode should log the entry. This would be quite noisy wouldn't it?

2024-12-21 02:31 UTC, namco1992 commented
> I don't agree that quiet mode should log the entry. This would be quite noisy wouldn't it?

I've thought about it too, so I only added it to the quiet mode so it only logs on the debug level. My train of thought is:
- The user can choose not to set log level to debug, if they want it to be "quiet", this behaviour is unchanged.
- When a user explicitly set the log level to debug, I assume that they would expect to see more details for debugging purposes, and the entry logged there would be helpful to reveal why there is an error.

2025-01-09 14:24 UTC, namco1992 commented
Hi @djaglowski, is there anything I can do to reopen this discussion? Or should I consider it as a "no no"? Thanks!

2025-01-21 18:53 UTC, djaglowski commented
If anything I would think an additional debug log in the "not quiet" cases might be appropriate. I seem to recall logging of entry contents was removed at some point due to security concerns, though I can't seem to find the PR so I may be misremembering. Maybe @ChrsMark has thoughts on this?

2025-01-22 09:30 UTC, ChrsMark commented
I think avoid printing the entries for security reasons makes sense. We would need to ensure that sensitive information would be sanitized etc.

Maybe an extra setting along with a separate log would help here for users that want to debug their entries.

2025-01-23 10:13 UTC, namco1992 commented
Hi @djaglowski @ChrsMark, I think security is a valid concern for sure. WDYT if we add an extra boolean field like `log_entry` to control the behaviour? The config would look like this:
```
- type: json_parser
  parse_from: body.message
  on_error: send
  log_entry: true
```

Then the `HandleEntryError` method could look like this:
```go
// HandleEntryError will handle an entry error using the on_error strategy.
func (t *TransformerOperator) HandleEntryError(ctx context.Context, entry *entry.Entry, err error) error {
	logFields := []zap.Field{zap.Any("error", err), zap.Any("action", t.OnError)}
	if t.LogEntry {
		logFields = append(logFields, zap.Any("entry", entry))
	}
	if t.OnError == SendOnErrorQuiet || t.OnError == DropOnErrorQuiet {
		t.Logger().Debug("Failed to process entry", logFields...)
	} else {
		t.Logger().Error("Failed to process entry", logFields...)
	}
	if t.OnError == SendOnError || t.OnError == SendOnErrorQuiet {
		writeErr := t.Write(ctx, entry)
		if writeErr != nil {
			err = fmt.Errorf("failed to send entry after error: %w", writeErr)
		}
	}

	return err
}
```

Do you think this is an acceptable solution? Thanks!

2025-02-12 11:58 UTC, namco1992 commented
not stale?

2025-03-15 05:20 UTC, closed without merging