Add extractors for cpu/mem metrics
open-telemetry/opentelemetry-collector-contrib pull request #3790
Opened 2021-06-15 15:01 UTC by pxaws

**Description:** <Describe what has changed.>
As a request to split the PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3414, we create a separate PR to add the extractors for cpu/mem metrics. 

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2307

**Testing:** <Describe what testing was performed and which tests were added.>
Unit tests.

2021-06-15 16:44 UTC, mxiamxia approved these changes
Thanks

2021-06-15 22:35 UTC, Aneurysm9 approved these changes

2021-06-16 12:44 UTC, bogdandrutu approved these changes
Please make sure you think how this interacts with host metrics, and why we need the same metrics extracted in multiple places.

2021-06-16 12:48 UTC, bogdandrutu requested changes
Please apply comments to all the unittests and testutils

2021-06-16 12:48 UTC, bogdandrutu commented on receiver/awscontainerinsightreceiver/internal/cadvisor/extractors/mem_extractor_test.go
> +	}
Why logging in unittests?

2021-06-16 12:48 UTC, bogdandrutu commented on receiver/awscontainerinsightreceiver/internal/cadvisor/testutils/helpers.go
> +	}
Consider to use assertions instead of logging in unittests.

2021-06-16 14:33 UTC, pxaws commented on receiver/awscontainerinsightreceiver/internal/cadvisor/extractors/mem_extractor_test.go
> +	}
I will remove it

2021-06-16 14:39 UTC, pxaws commented
> Please make sure you think how this interacts with host metrics, and why we need the same metrics extracted in multiple places.

Host metrics is a different type of metrics in our case because it comes from different resources. We do the extraction at a different places and use it to enrich to cadvisor metrics. Host metrics and cadvisor metrics are not the same metrics.

2021-06-16 15:02 UTC, pxaws commented
> Please apply comments to all the unittests and testutils

I have changed the tests accordingly

2021-06-16 15:50 UTC, bogdandrutu commented
>> Host metrics is a different type of metrics in our case because it comes from different resources. We do the extraction at a different places and use it to decorate cadvisor metrics. Host metrics and cadvisor metrics are not the same metrics.

Very vague response

2021-06-16 15:50 UTC, bogdandrutu approved these changes

2021-06-16 15:50 UTC, merged

2021-06-16 16:20 UTC, pxaws commented
> > > Host metrics is a different type of metrics in our case because it comes from different resources. We do the extraction at a different places and use it to decorate cadvisor metrics. Host metrics and cadvisor metrics are not the same metrics.
> 
> Very vague response

The cadvisor metrics are based on cgroup hierarchy and are stats about each containers (and its parent pods). To compute some percent metrics, we need to compare it with the host metrics.