internal/*: eliminate use of .Append()
open-telemetry/opentelemetry-collector-contrib pull request #3859
Opened 2021-06-22 16:54 UTC by Aneurysm9

**Description:** Removes use of deprecated `.Append()` methods.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/2488

2021-06-22 17:03 UTC, tigrannajaryan approved these changes

2021-06-22 18:18 UTC, jrcamp requested changes
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3860#pullrequestreview-689855727

2021-06-22 19:18 UTC, Aneurysm9 commented
> [#3860 (review)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3860#pullrequestreview-689855727)

I see how that may be applicable on that PR, but not for any of the changes here.  Can you illustrate how you think the changes in this PR can minimize allocations?  Does that need to be done at this time, or can it be treated as a separate optimization after eliminating the deprecated `Append()` method?   Once these PRs land we should be able to remove that method from the `pdata.*Slice` types.

2021-06-22 19:50 UTC, jrcamp commented
The batch one I don't know if there's anything that can be done for it but the other one can avoid the copy:

```diff
diff --git a/internal/aws/containerinsight/utils.go b/internal/aws/containerinsight/utils.go
index b08d55ba9..9e6761463 100644
--- a/internal/aws/containerinsight/utils.go
+++ b/internal/aws/containerinsight/utils.go
@@ -191,29 +191,21 @@ func ConvertToOTLPMetrics(fields map[string]interface{}, tags map[string]string,
 		unit := GetUnitForMetric(metric)
 		switch t := value.(type) {
 		case int:
-			tgt := ilms.AppendEmpty()
-			intGauge(key, unit, int64(t), timestamp).CopyTo(tgt)
+			intGauge(ilms.AppendEmpty(), key, unit, int64(t), timestamp)
 		case int32:
-			tgt := ilms.AppendEmpty()
-			intGauge(key, unit, int64(t), timestamp).CopyTo(tgt)
+			intGauge(ilms.AppendEmpty(), key, unit, int64(t), timestamp)
 		case int64:
-			tgt := ilms.AppendEmpty()
-			intGauge(key, unit, t, timestamp).CopyTo(tgt)
+			intGauge(ilms.AppendEmpty(), key, unit, t, timestamp)
 		case uint:
-			tgt := ilms.AppendEmpty()
-			doubleGauge(key, unit, float64(t), timestamp).CopyTo(tgt)
+			doubleGauge(ilms.AppendEmpty(), key, unit, float64(t), timestamp)
 		case uint32:
-			tgt := ilms.AppendEmpty()
-			doubleGauge(key, unit, float64(t), timestamp).CopyTo(tgt)
+			doubleGauge(ilms.AppendEmpty(), key, unit, float64(t), timestamp)
 		case uint64:
-			tgt := ilms.AppendEmpty()
-			doubleGauge(key, unit, float64(t), timestamp).CopyTo(tgt)
+			doubleGauge(ilms.AppendEmpty(), key, unit, float64(t), timestamp)
 		case float32:
-			tgt := ilms.AppendEmpty()
-			doubleGauge(key, unit, float64(t), timestamp).CopyTo(tgt)
+			doubleGauge(ilms.AppendEmpty(), key, unit, float64(t), timestamp)
 		case float64:
-			tgt := ilms.AppendEmpty()
-			doubleGauge(key, unit, t, timestamp).CopyTo(tgt)
+			doubleGauge(ilms.AppendEmpty(), key, unit, t, timestamp)
 		default:
 			valueType := fmt.Sprintf("%T", value)
 			logger.Warn("Detected unexpected field", zap.String("key", key), zap.Any("value", value), zap.String("value type", valueType))
@@ -223,9 +215,7 @@ func ConvertToOTLPMetrics(fields map[string]interface{}, tags map[string]string,
 	return md
 }
 
-func intGauge(metricName string, unit string, value int64, ts pdata.Timestamp) pdata.InstrumentationLibraryMetrics {
-	ilm := pdata.NewInstrumentationLibraryMetrics()
-
+func intGauge(ilm pdata.InstrumentationLibraryMetrics, metricName string, unit string, value int64, ts pdata.Timestamp) pdata.InstrumentationLibraryMetrics {
 	metric := initMetric(ilm, metricName, unit)
 
 	metric.SetDataType(pdata.MetricDataTypeIntGauge)
@@ -240,9 +230,7 @@ func intGauge(metricName string, unit string, value int64, ts pdata.Timestamp) p
 	return ilm
 }
 
-func doubleGauge(metricName string, unit string, value float64, ts pdata.Timestamp) pdata.InstrumentationLibraryMetrics {
-	ilm := pdata.NewInstrumentationLibraryMetrics()
-
+func doubleGauge(ilm pdata.InstrumentationLibraryMetrics, metricName string, unit string, value float64, ts pdata.Timestamp) pdata.InstrumentationLibraryMetrics {
 	metric := initMetric(ilm, metricName, unit)
 
 	metric.SetDataType(pdata.MetricDataTypeDoubleGauge)
```

2021-06-22 20:37 UTC, jrcamp approved these changes

2021-06-23 05:58 UTC, anuraaga approved these changes

2021-06-23 08:58 UTC, bogdandrutu approved these changes

2021-06-28 13:11 UTC, merged