fix(exporter/sentry): correctly set event ID to a random UUID.
open-telemetry/opentelemetry-collector-contrib pull request #4320
Opened 2021-07-24 12:46 UTC by fourbytes

**Description:** <Describe what has changed.>
Set Sentry event ID to a randomly generated UUID. This should fix #4141.

**Link to tracking Issue:** #4141

**Testing:**
 - Tested that traces were sent correctly to a live sentry instance.

**Documentation:** <Describe the documentation added.>

2021-07-30 06:04 UTC, tigrannajaryan commented
@AbhiPrasad please review.

2021-08-03 12:02 UTC, AbhiPrasad requested changes
Thanks for taking this on!

2021-08-03 12:02 UTC, AbhiPrasad commented on exporter/sentryexporter/sentry_exporter.go
> +
Prefer approach to https://github.com/getsentry/sentry-go/blob/8a528f85d1952e6690c627caec2efe7f010a6964/util.go#L15 so we don't have to bring in the uuid dep.

2021-08-24 05:22 UTC, fourbytes commented
Sorry for the delay. I've rebased and updated the uuid generation to the recommended method.

2021-08-30 04:48 UTC, fourbytes commented
As per my comment in issue #4141, I found a broader issue with the root span check logic. I *think* I've found a reasonable way to solve this by treating [spans that accept remote incoming parent spans](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind) as root spans. With this change I finally have traces from opentelemetry showing up perfectly in Sentry:

![image](https://user-images.githubusercontent.com/4339597/131286628-0c033d95-ea89-462f-9cb1-f5672b743e5b.png)

@AbhiPrasad this is ready for another review.

2021-09-07 19:25 UTC, AbhiPrasad approved these changes
Sorry for the delay, this looks good on the Sentry side. Thanks for your contribution!

2021-09-07 19:25 UTC, AbhiPrasad commented on exporter/sentryexporter/sentry_exporter.go
> +	return s.ParentSpanID() == pdata.SpanID{} || kind == pdata.SpanKindServer || kind == pdata.SpanKindConsumer
Can we make sure to update https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/sentryexporter/docs/transformation.md this new context?

Also, can we link to the opentelemetry spec about span kind in the code comments? Like what we do here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/21b423bfff56ca1e5d50e6b8f1f9f4929603695b/exporter/sentryexporter/sentry_exporter.go#L273

2021-09-07 22:58 UTC, AbhiPrasad commented
@bogdandrutu this is ready for general otel review btw - the doc changes aren’t a blocker and it’s important to get this merged in so that things work as expected.

2021-09-15 11:00 UTC, AbhiPrasad commented
@bogdandrutu ping?

2021-09-22 12:54 UTC, AbhiPrasad commented
@tigrannajaryan could you review?

2021-09-22 14:08 UTC, tigrannajaryan approved these changes

2021-09-22 17:05 UTC, tigrannajaryan commented
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4320/checks?check_run_id=3676312902:
```
sentry_exporter.go:252: File is not `gofmt`-ed with `-s` (gofmt)
		TraceID:      span.TraceID().Bytes(),
		SpanID:       span.SpanID().Bytes(),
		Description:  description,
		Op:           op,
		Tags:         tags,
		StartTime:    unixNanoToTime(span.StartTimestamp()),
		EndTime:      unixNanoToTime(span.EndTimestamp()),
		Status:       status,
```

2021-09-23 12:43 UTC, AbhiPrasad commented
@fourbytes could you take a look?

2021-09-30 17:06 UTC, bogdandrutu commented
Please rebase and fix lint issues.

2021-10-02 13:25 UTC, fourbytes commented
Rebased and gofmt'd!

2021-10-04 13:37 UTC, merged