Migrate hostmetricsreceiver from Collector core to Collector contrib
open-telemetry/opentelemetry-collector-contrib pull request #4660
Opened 2021-08-16 20:03 UTC by alexperez52

This PR migrates the hostmetricsreceiver component from the Collector core repository to the Collector contrib repository.

This PR retains the commit history from core and includes plumbing fixes for go.mod, makefile, components.go.

Related issues include: 
[opentelemetry-collector/#3474](https://github.com/open-telemetry/opentelemetry-collector/issues/3474)
[opentelemetry-collector/#3638](https://github.com/open-telemetry/opentelemetry-collector/issues/3638)

2021-08-16 21:14 UTC, alolita commented
Hi @bogdandrutu @tigrannajaryan based on our discussion last week, we're starting to file PRs to move each core component to contrib. Please review and merge. Thanks!

2021-08-17 07:56 UTC, mx-psi requested changes

2021-08-17 07:56 UTC, mx-psi commented on cmd/otelcontribcol/components.go
> +	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver"
You need to add a `replace` directive on the main `go.mod` file for this to work

2021-08-17 07:56 UTC, mx-psi commented on receiver/hostmetricsreceiver/codegen.go
> +//go:generate mdatagen metadata.yaml
I don't think we have the `mdatagen` tool on this repository, we will need to move it here first.

2021-08-17 07:56 UTC, mx-psi commented on receiver/hostmetricsreceiver/config_test.go
> +	"go.opentelemetry.io/collector/internal/processor/filterset"
This is an internal package from a different repository, so we need to move this over here first or find an alternative solution.

2021-08-23 01:28 UTC, closed without merging