Try to build an ARM64 image
open-telemetry/opentelemetry-collector-contrib pull request #4732
Opened 2021-08-19 08:52 UTC by gillg

**Description:** 
To be able installing otel-collector-contrib on ARM64 oriented nodes (like Amazon Graviton backed CPU) build an image for x64 and another for arm64.

**Notes for mainteners:**

I'm not sure if buildx is enabled on your pipeline platform...
Once done both images have to be pushed on remote repositories.

2021-08-19 21:42 UTC, bogdandrutu requested changes
Unfortunately we broke the main branch, need to do more work to rebase to the correct main

2021-08-23 09:50 UTC, gillg commented
@bogdandrutu my branch has been completly rebased on the last main branch.

2021-08-23 12:04 UTC, gillg commented on Makefile
> +	cp ./bin/$(COMPONENT)_* ./cmd/$(COMPONENT)/
We copy all binaries to handle more future platform if needed.

2021-08-23 12:04 UTC, gillg commented on cmd/otelcontribcol/Dockerfile
> +ARG TARGETOS TARGETARCH
Changing `buildx build --platform linux/amd64,linux/arm64` will automaticaly change these args, so we can add new platforms tomorrow if we build binaries for other platorms, just changing platforms targeted in the build command.

2021-08-23 12:04 UTC, gillg commented on Makefile
>  	GOOS=linux GOARCH=amd64 $(MAKE) $(COMPONENT)
Can't we reuse binaries from `otelcontribcol-all-sys` ? It avoids to declare manualy each platform to build.

2021-09-07 21:14 UTC, gillg commented
Hello ! Can I help with something here or improve something ? Does someone has plans to test this change in pipeline ?

2021-12-02 05:17 UTC, closed without merging