Patch 1
open-telemetry/opentelemetry-collector-contrib pull request #5061
Opened 2021-09-01 20:32 UTC by qingvincentyin

On AWS EKS 1.21, I'd get this error (from your original code):

```console
$ kubectl logs -f --tail=10 ds/otel-collector
 
2021-08-28T17:46:38.930Z	error	Failed to process entry	{"kind": "receiver", "name": "filelog", "operator_id": "$.extract_metadata_from_filepath", "operator_type": "regex_parser", "error": {"description": "Entry is missing the expected parse_from field.", "suggestion": "Ensure that all incoming entries contain the parse_from field.", "details": {"parse_from": "$attributes.file_path"}}, "action": "send", "entry": {"timestamp":"2021-08-28T17:22:14.809709717Z","body":{"log":"2021-08-28T17:22:14+0000 DEBUG This is a debug log that shows a log that can be ignored.\n","stream":"stdout"},"attributes":{"file.path":"/var/log/pods/default_random-logger_4cf99717-08db-425b-88b6-1ee98fdf3660/random-logger/0.log"},"severity":0}}
```

The error message is showing that the actual attribute is `file.path`, not `file_path`. My proposed fix will correct that.

**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

2021-09-02 07:11 UTC, mx-psi commented
@djaglowski can you have a look? Related to filelogreceiver

2021-09-15 17:39 UTC, qingvincentyin commented
Is anyone looking into this?

2021-09-15 18:53 UTC, djaglowski approved these changes
Thanks for pinging the thread. I missed this the first time around.

LGTM

2021-09-23 07:31 UTC, mx-psi requested changes
@qingvincentyin You need to update the PR name to a more descriptive message

2021-09-23 18:55 UTC, qingvincentyin commented
@mx-psi Done accordingly.

2021-09-24 07:50 UTC, mx-psi approved these changes
Thanks!

2021-09-30 17:06 UTC, merged