contrib/iinternal/coreinternal: add helpers for Pdata Metrics
open-telemetry/opentelemetry-collector-contrib pull request #5231
Opened 2021-09-13 23:05 UTC by odeke-em

Adds helper functions to help create metrics for OTLP
pdata translations. The need for these helpers comes
from PR #5184 in which we need to translate directly
from Prometheus->Pdata instead of Prometheus->OpenCensus->Pdata,
but we shall need to modify both receiver/prometheus*/internal and
the base directory.

This code is heavily used in the mentioned PR and thus no
tests included in this change.

Updates PR #5184

2021-09-13 23:06 UTC, odeke-em commented
Kindly help me with a blind review/approval here @dashpole @alolita @bogdandrutu @Aneurysm9 @codeboten as this code is used in the linked PR.

2021-09-13 23:19 UTC, codeboten approved these changes
👍

2021-09-14 00:11 UTC, MovieStoreGuy requested changes
To help show the value of this, can I kindly ask you to add tests to this?

2021-09-14 00:13 UTC, odeke-em commented
> To help show the value of this, can I kindly ask you to add tests to this?
> 
> 

In the PR subject I explain its purpose and particularly

> This code is heavily used in the mentioned PR and thus no
tests included in this change.

2021-09-14 00:22 UTC, MovieStoreGuy commented
If the code is heavily used in the mentioned PR then it should be tested here. Having heavily used code is not an excuse to not write tests.

2021-09-14 06:26 UTC, bogdandrutu reviewed
Consider to make this internal to the module that needs it for the moment.

2021-09-14 06:26 UTC, bogdandrutu commented on internal/coreinternal/metricstestutil/metricsutil_pdata.go
> +func DistPointPdata(ts pdata.Timestamp, bounds []float64, counts []uint64) *pdata.HistogramDataPoint {
Do not return pointer to pdata.

2021-09-14 06:26 UTC, bogdandrutu commented on internal/coreinternal/metricstestutil/metricsutil_pdata.go
> +func DistPointPdata(ts pdata.Timestamp, bounds []float64, counts []uint64) *pdata.HistogramDataPoint {
pdata usually benefits more if instead of constructing new Metric, you append it to a MetricSlice. Less allocations.

2021-09-14 06:27 UTC, bogdandrutu commented
Also +1 to @MovieStoreGuy comment about having tests.

2021-09-14 22:54 UTC, odeke-em commented
> If the code is heavily used in the mentioned PR then it should be tested here. Having heavily used code is not an excuse to not write tests.

I appreciate the enthusiasm and time to review @MovieStoreGuy and @bogdandrutu,. but this doesn't make sense to me, and seems like it is just being pedantic without context about what's happening. This code doesn't add new core code functionality. There is nothing unique about me just copying and pasting this code allover, this isn't code for pdata construction in our libraries, this would be literal helpers in my test code. It costs me much less time to just duplicate this functionality which doesn't add any surface area except in building points effectively. With that logic, all the test helpers should also be tested -- this doesn't hold up for any library, and doesn't add value for the end goals for which these libraries are already years behind in ditching OpenCensus.

2021-09-15 03:21 UTC, MovieStoreGuy commented
@odeke-em , the point of adding tests and smaller PRs is that things can be reviewed in isolation and build up to the larger context as (more bottom up than top down). It helps keeps things streamed line and the community can review with confidence. 

>  This code doesn't add new core code functionality.

From what I can tell with this git commit, it is for the project. 

>  this would be literal helpers in my test code

Aa, I had missed that, my apologies. It wasn't clear these methods were to be only used for tests purposes since the title of the PR and the method names themselves didn't help allude to that fact. 

Can I ask that you comment to that affect? Making it clear that these methods are to be used for testing purposes only?

2021-09-15 08:48 UTC, anuraaga commented
> With that logic, all the test helpers should also be tested

The reality is this is generally considered good practice - test helpers combine to become a test framework basically. Then we need to catch issues that affect the framework in the framework itself. For example, perhaps some refactoring affects `AppendEmpty` and breaks this logic - failures showing up with longer stack traces deep in unrelated code will make it very difficult to update this file. In fact, if the same logic was instead copied into five places, at least it's obvious that those five places need to be updated, instead of five unrelated places that you then have to navigate back to here. This is precisely the motivation for unit tests in software engineering.

This code isn't in `_test.go` files - it's unfortunate that we still haven't reenabled codecov since their security incident since it's great for verifying how we're doing. But the intent is to have a code coverage threshold - if the check was reenabled, this PR wouldn't even be mergable since it wouldn't pass the codecov threshold (applied since it's not `_test.go`).

They're simple functions and can use just some simple tests so it'd be great if you can add them. I appreciate that it is annoying to write tests - but let's just write them and move on :)

2021-09-15 17:37 UTC, bogdandrutu commented
@anuraaga as suggested:
1. This code should leave in an internal directory for the module that uses it until clear reason to share (even if this is called internalcore it is still shared).
2. The package name can be named "testmetricsutil" or something that suggest to be a testing package.
3. Usually I have test for testing packages as well see https://github.com/open-telemetry/opentelemetry-collector/tree/main/component/componenttest but I would not enforce that if this is internal only for that module, and marked accordingly as testing package.

2021-10-19 15:56 UTC, closed without merging