fix: remove squash on configtls.TLSClientSetting
open-telemetry/opentelemetry-collector-contrib pull request #5454
Opened 2021-09-27 18:56 UTC by hyunuk

**Description:**
This PR removes squash on`configtls.TLSClientSetting` and update yaml config/readme files since they are related to each other and they are addressed in the same PR to ensure that the unit test passed.

**Link to tracking Issue:**
#5433 and #5385

2021-09-27 23:28 UTC, bogdandrutu reviewed
Consider to split into a PR that fixes the broken readmes and other that change the other components to not squash

2021-09-27 23:35 UTC, hyunuk commented
@bogdandrutu I split them into the first two commits in this PR. 
But if they are splitted into two PRs, each of them cannot pass `build-and-test/unittest(pull_request)` in Github actions, which is labeled as `Required`.

2021-09-28 00:12 UTC, bogdandrutu commented on exporter/datadogexporter/example/example_k8s_manifest.yaml
> +          insecure: true
This his can be split.

2021-09-28 00:12 UTC, bogdandrutu commented on exporter/opencensusexporter/README.md
> +As a result, the following parameters are also required under `tls:`:
This his can be split.

2021-09-28 00:12 UTC, bogdandrutu commented on exporter/zipkinexporter/README.md
> +As a result, the following parameters are also required under `tls:`:
This his can be split.

2021-09-28 00:12 UTC, bogdandrutu commented on extension/oauth2clientauthextension/README.md
> +      key_file: keyfile
This his can be split.

2021-09-28 06:43 UTC, anuraaga approved these changes

2021-09-29 00:12 UTC, bogdandrutu requested changes
See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5466#pullrequestreview-766075718

2021-09-29 20:52 UTC, Aneurysm9 approved these changes

2021-09-30 15:38 UTC, bogdandrutu commented
Consider to split per component: splunk/observiq/elastic/aws, since this has approver from aws owners this may contain the aws changes, and create other 3 PRs. We need component owners to ack these changes.

2021-10-01 15:57 UTC, bogdandrutu approved these changes

2021-10-01 15:57 UTC, merged