Add expr language for logs and use it in filter processor
open-telemetry/opentelemetry-collector-contrib pull request #5680
Opened 2021-10-08 12:18 UTC by sumo-drosiek

**Description:**

- rename existing matcher to metric_matcher
- add matcher for logs with support for Body (as string), Name, SeverityNumber ans SeverityText
- use matcher in filterprocessor

**Link to tracking Issue:**
#5679 

**Testing:**

- unit tests

**Documentation:**

README

2021-10-15 11:41 UTC, sumo-drosiek commented
@jpkrohling pinging :)

2021-10-18 09:55 UTC, jpkrohling reviewed
This looks very cool, I didn't know we had it for metrics already! I have only one question about the security considerations, and they might be documented already as part of the metrics part. There are also a couple of minor things to adjust, but overall, this LGTM!

2021-10-18 14:19 UTC, jpkrohling approved these changes

2021-10-19 15:42 UTC, bogdandrutu requested changes
In general I like this approach, but @punya owes us the configuration for filtering that we should use for filter processors and for "transformation" processors.

2021-11-09 05:15 UTC, closed without merging