Add support for per cpu metrics
open-telemetry/opentelemetry-collector-contrib pull request #5756
Opened 2021-10-14 20:31 UTC by dloucasfx

Signed-off-by: Dani Louca <dlouca@splunk.com>

**Description:**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5243
With this change, the signalfx exporter is able to emit per core cpu metrics.
The dimension `cpu` exists for non-aggregated/per_core metrics

**Link to tracking Issue:** <Issue number if applicable>
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5243

**Documentation:** <Describe the documentation added.>

This config example will emit per core and aggregated `cpu.interrupt` metric

```
  signalfx:
    access_token: "********"
    api_url: "https://api.us0.signalfx.com"
    ingest_url: "https://ingest.us0.signalfx.com"
    include_metrics:
      - metric_name: "cpu.interrupt"
```

This config example will emit per core only `cpu.interrupt` metric
```
 signalfx:
    access_token: "********"
    api_url: "https://api.us0.signalfx.com"
    ingest_url: "https://ingest.us0.signalfx.com"
    include_metrics:
      - metric_name: "cpu.interrupt"
        dimensions:
          cpu: ["*"]
```

2021-10-14 21:40 UTC, mstumpfx approved these changes

2021-10-14 22:31 UTC, tigrannajaryan approved these changes

2021-10-14 22:32 UTC, tigrannajaryan commented
The test failed: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5756/checks?check_run_id=3899988031

2021-10-14 23:11 UTC, bogdandrutu approved these changes

2021-10-15 00:17 UTC, dmitryax requested changes

2021-10-15 00:47 UTC, dmitryax commented
Should we also mention these configuration options to the README?

2021-10-15 03:05 UTC, dmitryax approved these changes
LGTM. It would be nice to have these examples mentioned in the docs

2021-10-15 17:40 UTC, bogdandrutu approved these changes

2021-10-15 17:40 UTC, merged