Fetch all annotations and labels for pods and namespaces in k8sattributes processor
open-telemetry/opentelemetry-collector-contrib pull request #5780
Opened 2021-10-17 17:42 UTC by chaitanyaphalak

**Description:** 
Added the ability to fetch all annotations and labels from pods and namespace for k8stagger/k8sattributes processor

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4953

**Testing:** Added relevant Unit tests

**Documentation:** Added relevant docs and config examples

2021-10-19 03:17 UTC, anuraaga approved these changes

2021-10-29 06:14 UTC, dmitryax approved these changes

2021-10-29 11:07 UTC, owais requested changes

2021-10-29 16:51 UTC, owais approved these changes

2021-10-30 16:22 UTC, dmitryax commented on processor/k8sattributesprocessor/factory.go
> +	}
I think this should work:

```
for _, r := range append(oCfg.Extract.Labels, oCfg.Extract.Annotations...) {
	if r.Key != "" && r.KeyRegex != "" {
		return fmt.Errorf("Out of Key or KeyRegex only one option is expected to be configured at a time, currently Key:%s and KeyRegex:%s", r.Key, r.KeyRegex)
	}
}
```

No need for `nil` checks. Please try this out

2021-11-01 18:01 UTC, dmitryax approved these changes

2021-11-01 19:19 UTC, tigrannajaryan commented
Some build actions are failing. Please check.

2021-11-02 00:03 UTC, chaitanyaphalak commented
@tigrannajaryan fixed some build actions, the rest which are failing will be fixed by this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6091 - looks like they are failing for everyone.

2021-11-02 12:42 UTC, tigrannajaryan commented
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6091 is merged, please rebase to fix the build.

2021-11-02 22:03 UTC, chaitanyaphalak commented
@tigrannajaryan its ready!

2021-11-02 23:08 UTC, merged

2021-11-02 23:08 UTC, tigrannajaryan commented
Merged. Thanks @chaitanyaphalak 

For future PRs please make sure to populate the commit message (not just one line). The PR description is usually fine as a commit message. I copy/pasted this time.