Added obsrecv to Google Cloud Spanner receiver instead of error logging in collectData().
open-telemetry/opentelemetry-collector-contrib pull request #5831
Opened 2021-10-19 10:10 UTC by ydrozhdzhal

Fixed TODO made in previous MR. As it was requested by @tigrannajaryan:

This can flood the logs: https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#logging

Use obsreport instead to make the component observable and emit metrics on errors. See for example how OTLP receiver does it: https://github.com/open-telemetry/opentelemetry-collector/blob/55700930f9a3dc272b431cdbe2435f250cd5b5e0/receiver/otlpreceiver/internal/metrics/otlp.go#L63

2021-10-19 11:17 UTC, kostia-hospodarysko approved these changes

2021-10-19 14:48 UTC, bogdandrutu requested changes
Please change to use scraperhelper package as all the other packages, it comes for free with error reports (obsreport) and is consistent with all the other scrapers. See redis/kafka etc as examples.

2021-10-21 07:27 UTC, ydrozhdzhal commented
@bogdandrutu , small update from my side - in progress with one approach - will notify when it is ready(probably will create another MR and close this one at the moment of readiness).

2021-10-21 17:02 UTC, ydrozhdzhal commented
@bogdandrutu , O am closing this, since I introduced requested changes(by your request) here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5868

2021-10-21 17:02 UTC, closed without merging