[metrictransformprocessor] Use null to require absent label
open-telemetry/opentelemetry-collector-contrib pull request #6204
Opened 2021-11-08 20:00 UTC by punya

Previously, the code checked whether a label should be absent
by checking whether the string/regex matched the empty string.
This is slightly surprising for exact matches and (IMO) very surprising
for regex matches.

This PR changes the label matcher to use YAML null to configure a
label that must be absent. Blank strings and regexes that match
blank strings are no longer treated specially.

This came up while I was reviewing the code for a migration to pdata.
I'm submitting a separate PR because I want to keep functional
changes separate from the change in internal data representation.

**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

2021-11-08 20:02 UTC, punya commented
@hossain-rayhan how do you feel about this change?

2021-11-09 20:03 UTC, hossain-rayhan commented
Thanks @punya. This looks good to me.

2021-11-09 20:03 UTC, hossain-rayhan approved these changes

2021-11-09 20:08 UTC, Aneurysm9 approved these changes

2021-11-10 18:03 UTC, bogdandrutu requested changes
As you know @punya, I am waiting for you and @anuraaga to finish the config for transform processors.

2021-11-12 01:56 UTC, closed without merging