[receivers/hostmetrics] Fix set of attributes for system.cpu.time metric
open-telemetry/opentelemetry-collector-contrib pull request #6422
Opened 2021-11-24 00:15 UTC by dmitryax

Define correct set of attributes for system.cpu.time metric in metadata.yaml

2021-11-24 08:34 UTC, mx-psi requested changes
needs `make generate`

2021-11-24 17:09 UTC, dmitryax commented
@mx-psi it's just depends on this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6423

Rebased. PTAL

2021-11-24 17:23 UTC, mx-psi approved these changes

2021-11-29 22:16 UTC, bogdandrutu approved these changes

2021-11-29 22:16 UTC, merged