sfx exporter: group new metric translations by dimensions
open-telemetry/opentelemetry-collector-contrib pull request #704
Opened 2020-08-13 15:08 UTC by pmcollins

**Description:**
The first implementation of the new metric translator grabbed one match
of each of the first and second operands without regard to whether
their dimensions matched.

This update groups operand pairs by matching dimensions. An operand pair
will be considered only if their dimensions match. As a result, multiple
pairs are also now supported.

**Testing:** Unit tests added.

2020-08-13 22:15 UTC, dmitryax approved these changes

2020-08-14 21:14 UTC, dmitryax requested changes
Doesn't work as expected after manual validation

2020-08-14 22:39 UTC, pmcollins commented
Now doing an explicit test for dimension equality.

2020-08-14 22:54 UTC, dmitryax approved these changes

2020-08-15 00:06 UTC, merged