Add support to skip TLS verification in Datadog exporter
open-telemetry/opentelemetry-collector-contrib pull request #7422
Opened 2022-01-28 16:58 UTC by julien-lebot

**Description:**
This PR adds an option to disable TLS verification. This was requested in the following issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6235.

**Link to tracking Issue:** [6235
](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6235)
**Testing:** Added 2 basic unit tests.

**Documentation:** Updated the example configuration.

2022-02-03 12:13 UTC, mx-psi reviewed
Just one small comment, otherwise looks good!

2022-02-03 12:13 UTC, mx-psi commented on exporter/datadogexporter/config/config.go
> +}
The config struct is considered part of the public API and therefore we won't be able to make breaking changes to it in the future. To future-proof, we should put this in a `LimitedHTTPClientSettings` like

```go
type LimitedHTTPClientSettings struct {
	TLSSetting LimitedTLSClientSettings `mapstructure:"tls,omitempty"`
}
```

and then embed it on the `Config` struct:

```go
LimitedHTTPClientSettings `mapstructure:",squash"`
```

This results in the same YAML configuration but we future-proof the Go API too.

2022-02-04 09:44 UTC, mx-psi commented
I updated the title to conform to guidelines

2022-02-08 17:42 UTC, codeboten reviewed
Any reason not to use the already defined `TLSClientSetting` and only support the flags that are needed from that configuration?

https://github.com/open-telemetry/opentelemetry-collector/blob/18fb01178b794a0b8e2f3b0e48ab6f81056ae2b5/config/configtls/configtls.go#L58

2022-02-09 08:46 UTC, mx-psi approved these changes
LGTM, just a minor correction on the changelog. I agree with @julien-lebot on why we want to use the `Limited*` pattern (which is already in use in the CloudFoundry receiver). 

An alternative would be to use the `configtls.TLSClientSettings` and fail to unmarshal/validate if any fields we don't support are set, however, I don't see how we would do that, at least not in a way that works over time (each time a new setting is added we would need to 'ban it' manually).

2022-02-09 08:46 UTC, mx-psi commented on CHANGELOG.md
> +- `datadogexporter`: Add insecure_skip_tls flag to configuration (#7422)
```suggestion
- `datadogexporter`: Add insecure_skip_verify flag to configuration (#7422)
```

2022-02-09 09:30 UTC, jpkrohling commented
Looks like I can't change the code from this PR, thus, I can't fix the changelog conflicts for you. Please rebase this PR.

2022-02-09 16:20 UTC, jpkrohling requested changes

2022-02-09 16:20 UTC, jpkrohling commented on CHANGELOG.md
> +- `datadogexporter`: Add insecure_skip_verify flag to configuration (#7422)
This should not be part of the 0.44.0 block, it should be under unreleased.

2022-02-09 16:30 UTC, jpkrohling approved these changes

2022-02-09 16:38 UTC, codeboten approved these changes

2022-02-09 18:24 UTC, merged