sumologicexporter: move config validation to config
open-telemetry/opentelemetry-collector-contrib pull request #7936
Opened 2022-02-16 08:15 UTC by sumo-drosiek

**Description:**
Add validation to Config

**Link to tracking Issue:**
#7845

**Testing:**
unit tests

**Documentation:**
N/A

2022-02-16 19:24 UTC, codeboten reviewed
Thanks for the change, please address the lint failure.

2022-02-17 08:02 UTC, pmm-sumo approved these changes

2022-02-17 10:16 UTC, jpkrohling requested changes
I can't seem to be able to change this PR, so, I can't update the changelog for you. Please, move the entry to the unreleased section.

2022-02-17 10:26 UTC, sumo-drosiek commented
@jpkrohling should be better now

2022-02-17 10:26 UTC, jpkrohling approved these changes

2022-02-17 12:59 UTC, merged