[exporters/datadog] Added ClusterRole and ClusterRoleBinding for otel-collector
open-telemetry/opentelemetry-collector-contrib pull request #8186
Opened 2022-03-01 09:43 UTC by kurtburak

**Description:** 
ClusterRole and ClusterRoleBinding have been added to example_k8s_manifest.yaml to fix rbac errors in otel-collector pod.

Errors:
W0301 08:39:49.359379       1 reflector.go:324] k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:open-telemetry:default" cannot list resource "pods" in API group "" at the cluster scope
E0301 08:39:49.359460       1 reflector.go:138] k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:open-telemetry:default" cannot list resource "pods" in API group "" at the cluster scope

**Link to tracking Issue:**
n/a

**Testing:** 
Tested in local kind k8s cluster

**Documentation:**
n/a

2022-03-01 13:46 UTC, mackjmr commented
Thanks for the PR @kurtburak! I tested the new config and needed to make a couple changes:

1 - Change new line 41 from:
```
endpoint: "otel-collector.default:4317"
```
to 
```
endpoint: "otel-collector.open-telemetry:4317"
```
This prevents error:

> 2022-03-01T12:58:12.532Z        info    exporterhelper/queued_retry.go:215      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup otel-collector.default on 10.96.0.10:53: no such host\"", "interval": "6.171697115s"}

2 - Add `namespace: open-telemetry` under new line 216 (otel-collector Deployment). This prevents error:
```
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                  From                   Message
  ----     ------        ----                 ----                   -------
  Warning  FailedCreate  36s (x17 over 6m4s)  replicaset-controller  Error creating: pods "otel-collector-5645b8884f-" is forbidden: error looking up service account default/opentelemetry-collector: serviceaccount "opentelemetry-collector" not found
```

Other than these two changes, looks good to me 👍

2022-03-01 15:51 UTC, kurtburak commented
> [mackjmr](/mackjmr)

Thanks @mackjmr. I have updated the files.

2022-03-02 09:57 UTC, mx-psi reviewed
Can you add a changelog entry for this @kurtburak? I will try to test this and approve it by the end of the week

2022-03-02 18:52 UTC, pmm-sumo commented on CHANGELOG.md
> -- `groupbyattrsprocesor`: Allow empty keys, which allows to use the processor for compaction (#7793)
I guess that resolving conflicts went wrong here?

2022-03-02 18:53 UTC, pmm-sumo requested changes
Seems that recent `groupbyattrsprocessor` changes were removed by accident. Can you fix that?

2022-03-02 20:42 UTC, pmm-sumo approved these changes, later dismissed
`groupbyattrs` conflict is fixed now, which was my main concern for the previous review. I did a smoke test of the manifest (very basic, just checking if pods run without errors), looked OK

Still missing the changelog entry though @kurtburak

2022-03-02 20:48 UTC, pmm-sumo commented
@kurtburak thanks for updating the changelog, it seems that something went wrong and manifest is gone though

2022-03-02 20:52 UTC, pmm-sumo approved these changes

2022-03-02 21:31 UTC, kurtburak commented
Things went wrong but finally I have fixed them :)
Thanks a lot @mackjmr @pmm-sumo

2022-03-03 09:53 UTC, mx-psi approved these changes

2022-03-03 09:54 UTC, mx-psi commented
Thanks for doing this @kurtburak ! I am marking this as ready to merge, no need to fix changelog conflicts

2022-03-03 10:41 UTC, kurtburak commented
> Thanks for doing this @kurtburak ! I am marking this as ready to merge, no need to fix changelog conflicts (will be done by the maintainer that merges this)

Thanks @mx-psi . So I am waiting right? Because I am not authorized merge this PR.

2022-03-03 10:45 UTC, mx-psi commented
> So I am waiting right? Because I am not authorized to merge this PR.

Yes, a maintainer will give a final look and merge this (only them are authorized to merge PRs)

2022-03-04 16:31 UTC, codeboten approved these changes

2022-03-04 16:31 UTC, merged