Integrate nginxreceiver
open-telemetry/opentelemetry-collector-contrib pull request #9572
Opened 2022-04-28 18:09 UTC by nslaughter

**Description:** 
The nginx receiver was not previously included in the registration of components in `internal/components/components.go` and therefore was not building in the collector.

**Link to tracking Issue:** 
[issue 108 in the releases repo](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/108) explains. 

**Testing:** 
There were pre-existing unit and integration tests of the package which were passing and continue to pass after changes. I also added an entry for this receiver in `internal/components/receivers_test.go,` which tests the receiver lifecycle.

**Documentation:** 
I have not expanded upon existing documentation.

2022-04-28 20:43 UTC, pmm-sumo commented
Thank you for the contribuion @nslaughter, could you sign the CLA per the [contributing guidelines](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#sign-the-cla)?

2022-04-28 21:11 UTC, nslaughter commented
> Thank you for the contribuion @nslaughter, could you sign the CLA per the [contributing guidelines](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#sign-the-cla)?

Indeed. It's in progress with company approver.

2022-05-02 20:35 UTC, codeboten requested changes
Looks like something happen during rebase, please fix

2022-05-02 20:52 UTC, nslaughter commented
Thank you. It's fixed.

2022-05-02 22:58 UTC, dmitryax commented
Please resolve conflicts

2022-05-03 16:47 UTC, nslaughter commented
I'm tending to CI issues blocking now. ty.

2022-05-03 19:24 UTC, dmitryax commented
@nslaughter please also sign CLA to be able to contribute in OTel

2022-05-03 19:53 UTC, nslaughter commented on go.mod
> +	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nginxreceiver v0.0.0-00010101000000-000000000000
fixed

2022-05-03 20:08 UTC, nslaughter commented
Are there issues with any load tests or do failures indicate a problem with some change?
I'm wondering as the PR doesn't change Carbon or SignalFx related code, but the TestMetric10kDPS tests are failing for each.

2022-05-03 20:45 UTC, codeboten approved these changes
Just a minor comment, otherwise this looks good

2022-05-03 20:45 UTC, codeboten commented on internal/components/receivers_test.go
> +
nit:
```suggestion
```

2022-05-03 21:47 UTC, nslaughter commented on go.mod
> +	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/nginxreceiver v0.0.0-00010101000000-000000000000
Unfortunately that is my mistake and it is now in [this new commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9572/commits/e7f047503a7bd3bd7850cd302ce35e20c1641bfb).

2022-05-03 21:55 UTC, dmitryax approved these changes

2022-05-04 15:11 UTC, merged